#!/usr/bin/env bash
# Generated by bin/build-doctor-fixtures.py — do not edit by hand.
set -euo pipefail
: "${HARNESS_FAKE_HOME:?HARNESS_FAKE_HOME must be set}"
: "${REPO_ROOT:?REPO_ROOT must be set}"
mkdir -p "$HARNESS_FAKE_HOME/.local/share/cctally"
mkdir -p "$HARNESS_FAKE_HOME/.claude"
mkdir -p "$HARNESS_FAKE_HOME/.local/bin"
# The harness sets CCTALLY_AS_OF before invoking doctor, so all
# "age" computations in the report are deterministic.

# Helper: write a minimal .credentials.json that satisfies the
# OAuth presence check (_resolve_oauth_token: file source with
# {"claudeAiOauth":{"accessToken":"..."}}). Token value is
# synthetic — doctor never makes a real OAuth call.
write_oauth_credentials() {
  mkdir -p "$HARNESS_FAKE_HOME/.claude"
  cat > "$HARNESS_FAKE_HOME/.claude/.credentials.json" <<'JSON'
{"claudeAiOauth":{"accessToken":"fixture-token-not-real"}}
JSON
}

# Shim `security` so keychain lookups can't leak host OAuth state
# into doctor output. Without this, on a macOS dev box where the
# user is logged into Claude Code, every scenario would falsely
# show OAuth=present regardless of fixture intent. The shim is
# in PATH ahead of /usr/bin so it always wins.
cat > "$HARNESS_FAKE_HOME/.local/bin/security" <<'SH'
#!/usr/bin/env bash
# No-op shim — keychain unavailable in doctor fixtures.
exit 1
SH
chmod +x "$HARNESS_FAKE_HOME/.local/bin/security"

# Helper: write CC settings.json with canonical PostToolBatch/Stop/SubagentStop
# entries that _is_cctally_hook_command recognizes (matcher + nested
# hooks[].type=command + command). This is the shape `cctally setup`
# writes; the hook counter ignores anything else.
write_canonical_settings() {
  local path="$1"
  cat > "$path" <<'JSON'
{
  "hooks": {
    "PostToolBatch": [
      {"matcher": "*", "hooks": [{"type": "command", "command": "cctally hook-tick"}]}
    ],
    "Stop": [
      {"matcher": "", "hooks": [{"type": "command", "command": "cctally hook-tick"}]}
    ],
    "SubagentStop": [
      {"matcher": "", "hooks": [{"type": "command", "command": "cctally hook-tick"}]}
    ]
  }
}
JSON
}
# Seed install + hooks + OAuth + valid update-state + 1 fresh snapshot.
# Symlink every cctally-* binary so install.symlinks is OK.
for name in cctally cctally-alerts cctally-dashboard \
           cctally-dollar-per-percent cctally-five-hour-blocks \
           cctally-five-hour-breakdown cctally-forecast cctally-project \
           cctally-refresh-usage cctally-release cctally-sync-week \
           cctally-tui cctally-update; do
    ln -sf "$REPO_ROOT/bin/$name" "$HARNESS_FAKE_HOME/.local/bin/$name"
done
# CC settings.json — canonical hook shape that _is_cctally_hook_command
# recognizes (matcher + hooks[].type=command + command).
write_canonical_settings "$HARNESS_FAKE_HOME/.claude/settings.json"
write_oauth_credentials
# Fresh weekly snapshot 2s before CCTALLY_AS_OF
python3 "$REPO_ROOT/bin/build-doctor-fixtures.py" --emit-snapshot all_ok \
    "$HARNESS_FAKE_HOME/.local/share/cctally/stats.db"
