"""RED/GREEN coverage for provider-aware CLI share snapshots."""
from __future__ import annotations

from datetime import datetime, timezone
import json
import os
from pathlib import Path
import re
import runpy
import shutil
import stat
import subprocess
import sys
from types import SimpleNamespace

import pytest

from conftest import load_script
from _lib_source_analytics import (
    CodexRangeData,
    CodexReportData,
    CodexReportRow,
    CodexReportSeries,
    SourceResult,
    TokenTotals,
)


UTC = timezone.utc


def _kernel():
    ns = load_script()
    return ns, ns["_share_load_lib"](), ns["_cctally_source_analytics"]


def _period(ls):
    return ls.PeriodSpec(
        start=datetime(2026, 7, 1, tzinfo=UTC),
        end=datetime(2026, 7, 2, tzinfo=UTC),
        display_tz="UTC",
        label="Jul 01 → Jul 02 (UTC)",
    )


def _collision_snapshot(ls):
    return ls.ShareSnapshot(
        cmd="project",
        title="Projects",
        subtitle=None,
        period=_period(ls),
        columns=(
            ls.ColumnSpec(key="project", label="Project", kind="project"),
            ls.ColumnSpec(key="cost", label="$ Cost", align="right"),
        ),
        rows=(
            ls.Row(cells={
                "project": ls.ProjectCell("repo", rank_cost=1.0, identity="root-a"),
                "cost": ls.MoneyCell(1.0),
            }),
            ls.Row(cells={
                "project": ls.ProjectCell("repo", rank_cost=2.0, identity="root-b"),
                "cost": ls.MoneyCell(2.0),
            }),
        ),
        chart=ls.HorizontalBarChart(
            points=(
                ls.ChartPoint("repo", 0.0, 1.0, project_label="repo", project_identity="root-a"),
                ls.ChartPoint("repo", 1.0, 2.0, project_label="repo", project_identity="root-b"),
            ),
            x_label="$ Cost",
        ),
        totals=(),
        notes=(),
        generated_at=datetime(2026, 7, 2, 12, tzinfo=UTC),
        version="1.0.0",
    )


def test_equal_labels_with_distinct_qualified_identities_get_distinct_aliases():
    _ns, ls, _source = _kernel()

    scrubbed = ls._scrub(_collision_snapshot(ls), reveal_projects=False)

    row_labels = [row.cells["project"].label for row in scrubbed.rows]
    point_labels = [point.project_label for point in scrubbed.chart.points]
    assert set(row_labels) == {"project-1", "project-2"}
    assert point_labels == row_labels
    assert all(label != "repo" for label in point_labels)


def test_legacy_none_identity_snapshot_is_byte_stable():
    _ns, ls, _source = _kernel()
    snap = ls.ShareSnapshot(
        cmd="report",
        title="Legacy share",
        subtitle=None,
        period=_period(ls),
        columns=(ls.ColumnSpec(key="label", label="Label"),),
        rows=(ls.Row(cells={"label": ls.TextCell("value")}),),
        chart=None,
        totals=(),
        notes=(),
        generated_at=datetime(2026, 7, 2, 12, tzinfo=UTC),
        version="1.0.0",
    )

    assert ls.render(snap, format="md", theme="light", branding=True, reveal_projects=True) == (
        "---\n"
        "title: Legacy share\n"
        "generated_at: 2026-07-02T12:00:00Z\n"
        "period: 2026-07-01T00:00:00Z..2026-07-02T00:00:00Z\n"
        "panel: report\n"
        "anonymized: false\n"
        "cctally_version: 1.0.0\n"
        "---\n"
        "# Legacy share\n"
        # #503 S2 D1: the facts strip and the timestamp are unconditional.
        # This snapshot carries no project names, so D5 omits the privacy
        # clause rather than claiming a state it has no basis for.
        "_2026-07-01 → 2026-07-02 (UTC)_\n"
        "_2026-07-02T12:00:00Z_\n"
        "\n"
        "| Label |\n"
        "|:---|\n"
        "| value |\n"
        "\n"
        "_Generated by [cctally](https://github.com/omrikais/cctally) · v1.0.0 · 2026-07-02T12:00:00Z_\n"
    )


def test_codex_snapshot_labels_source_and_unavailable_reason_in_every_format():
    ns, ls, source = _kernel()
    warning = ns["SourceWarning"]("metadata", "Codex metadata is unavailable.")
    result = ns["SourceResult"]("codex", "unavailable", None, (warning,))

    snap = source.build_source_share_snapshot("project", result, reveal_projects=False)

    assert snap.source == "codex"
    assert snap.source_label == "Codex"
    assert snap.availability == "unavailable"
    assert snap.availability_reason == "Codex metadata is unavailable."
    for fmt in ("md", "html", "svg"):
        rendered = ls.render(snap, format=fmt, theme="light", branding=True, reveal_projects=True)
        assert "Codex" in rendered
        assert "Unavailable: Codex metadata is unavailable." in rendered


def test_populated_codex_report_snapshot_exposes_safe_quota_rows():
    _ns, _ls, source = _kernel()
    at = datetime(2026, 7, 2, 12, tzinfo=UTC)
    result = SourceResult(
        "codex",
        "ok",
        CodexReportData(
            as_of=at,
            series=(CodexReportSeries(
                quota_key="quota:never-render-this-opaque-key",
                slot="five-hour",
                window_minutes=300,
                rows=(CodexReportRow(
                    block_start=datetime(2026, 7, 2, 7, tzinfo=UTC),
                    reset_at=at,
                    used_percent=37.0,
                    cost_usd=4.25,
                    cost_per_percent=4.25 / 37,
                    status="ok",
                ),),
            ),),
            quota_status="ok",
        ),
    )

    snap = source.build_source_share_snapshot("report", result, reveal_projects=False)

    assert [column.key for column in snap.columns] == ["series", "used", "cost"]
    assert len(snap.rows) == 1
    assert snap.rows[0].cells["series"].text == "five-hour · 300m"
    assert snap.rows[0].cells["used"].text == "37.0%"
    assert "quota:never-render-this-opaque-key" not in " ".join(
        getattr(cell, "text", "") for cell in snap.rows[0].cells.values()
    )


def test_range_cost_share_without_breakdown_keeps_truthful_total_in_all_formats():
    _ns, ls, source = _kernel()
    start = datetime(2026, 7, 1, tzinfo=UTC)
    end = datetime(2026, 7, 2, tzinfo=UTC)
    result = SourceResult(
        "codex",
        "ok",
        CodexRangeData(
            start=start,
            end=end,
            totals=TokenTotals(total_tokens=1234, cost_usd=4.25),
            models=(),
            include_breakdown=False,
        ),
    )

    snap = source.build_source_share_snapshot("range-cost", result, reveal_projects=False)

    assert len(snap.rows) == 1
    assert snap.rows[0].cells["model"].text == "Total"
    assert snap.rows[0].cells["tokens"].text == "1,234"
    assert snap.rows[0].cells["cost"].usd == 4.25
    for fmt in ("md", "html", "svg"):
        rendered = ls.render(snap, format=fmt, theme="light", branding=True, reveal_projects=True)
        assert "1,234" in rendered
        assert "$4.25" in rendered


def test_codex_diff_share_keeps_each_native_row_status_and_ab_delta_metrics():
    ns, ls, source = _kernel()
    kernel = ns["_lib_source_analytics"]
    start = datetime(2026, 7, 1, tzinfo=UTC)
    middle = datetime(2026, 7, 1, 12, tzinfo=UTC)
    end = datetime(2026, 7, 2, tzinfo=UTC)
    entry = kernel.QualifiedCodexEntry
    entries = kernel.assign_collision_safe_project_labels((
        entry(
            timestamp=start, source_root_key="root-a", conversation_key="conversation-a",
            project_key="project:" + "a" * 24, project_label="repo", model="gpt-5",
            input_tokens=100, cached_input_tokens=20, output_tokens=30,
            reasoning_output_tokens=5, total_tokens=130, cost_usd=1.0,
        ),
        entry(
            timestamp=middle, source_root_key="root-b", conversation_key="conversation-b",
            project_key="project:" + "b" * 24, project_label="repo", model="gpt-5.5",
            input_tokens=200, cached_input_tokens=100, output_tokens=60,
            reasoning_output_tokens=10, total_tokens=260, cost_usd=3.0,
        ),
    ))
    result = kernel.build_codex_diff_result(
        entries,
        kernel.AnalyticsWindow("A", "calendar", start, middle),
        kernel.AnalyticsWindow("B", "calendar", middle, end),
        show_all=True,
        classify_presence=True,
    )

    snap = source.build_source_share_snapshot("diff", result, reveal_projects=False)
    for fmt in ("md", "html", "svg"):
        rendered = ls.render(snap, format=fmt, theme="light",
                             branding=True, reveal_projects=False)
        metrics = (
            ("A $", "B $", "Δ $", "Cost", "A", "B", "Δ", "Tokens")
            if fmt == "svg" else
            ("A $ Cost", "B $ Cost", "Δ $ Cost", "A Tokens", "B Tokens", "Δ Tokens")
        )
        labels = ("project-",) if fmt == "svg" else ("project-1", "project-2")
        for text in (*metrics, "gpt-5", "gpt-5.5", "dropped", "new", *labels):
            assert text in rendered
        assert "root-a" not in rendered and "root-b" not in rendered


def test_qualified_identity_uses_one_alias_across_cell_column_and_chart():
    _ns, ls, _source = _kernel()
    snap = ls.ShareSnapshot(
        cmd="project",
        title="Projects",
        subtitle=None,
        period=_period(ls),
        columns=(
            ls.ColumnSpec(key="project", label="Project"),
            ls.ColumnSpec(
                key="root-a", label="repo", kind="project",
                project_identity="project:aaaaaaaaaaaaaaaaaaaaaaaa",
            ),
        ),
        rows=(ls.Row(cells={
            "project": ls.ProjectCell(
                "repo", rank_cost=4.0,
                identity="project:aaaaaaaaaaaaaaaaaaaaaaaa",
            ),
            "root-a": ls.MoneyCell(4.0),
        }),),
        chart=ls.HorizontalBarChart(
            points=(ls.ChartPoint(
                "repo", 0.0, 4.0, project_label="repo",
                project_identity="project:aaaaaaaaaaaaaaaaaaaaaaaa",
            ),),
            x_label="$ Cost",
        ),
        totals=(), notes=(),
        generated_at=datetime(2026, 7, 2, 12, tzinfo=UTC), version="1.0.0",
    )

    scrubbed = ls._scrub(snap, reveal_projects=False)

    assert scrubbed.rows[0].cells["project"].label == "project-1"
    assert scrubbed.columns[1].label == "project-1"
    assert scrubbed.chart.points[0].project_label == "project-1"


def test_all_source_share_composes_claude_then_codex_without_all_snapshot(monkeypatch):
    ns, _ls, source = _kernel()
    emitted = []
    monkeypatch.setitem(ns, "_emit", lambda content, *, kind, value: emitted.append(content))
    monkeypatch.setitem(ns, "_share_resolve_version", lambda: "1.0.0")
    args = SimpleNamespace(
        command="project", source="all", format="md", theme="light",
        no_branding=False, reveal_projects=False, output="-", copy=False,
        open_after_write=False, project=None,
    )
    claude = ns["SourceResult"]("claude", "empty", {"projects": []})
    codex = ns["SourceResult"](
        "codex", "unavailable", None,
        (ns["SourceWarning"]("metadata", "Codex metadata is unavailable."),),
    )

    assert source._emit_source_result(args, codex, claude=claude) == 0

    assert len(emitted) == 1
    artifact = emitted[0]
    assert artifact.index("Claude") < artifact.index("Codex")
    assert "No data" in artifact
    assert "Unavailable: Codex metadata is unavailable." in artifact
    assert 'source="all"' not in artifact


@pytest.mark.parametrize("fmt", ("md", "html", "svg"))
@pytest.mark.parametrize(
    ("command", "argv", "handler_name", "payload", "expected"),
    [
        (
            "diff",
            ["diff", "--a", "2026-07-01..2026-07-01", "--b", "2026-07-02..2026-07-02"],
            "_cmd_diff_claude",
            {
                "sections": [{
                    "name": "overall",
                    "rows": [{
                        "label": "Overall",
                        "a": {"cost_usd": 1.25, "tokens_input": 100},
                        "b": {"cost_usd": 2.50, "tokens_input": 200},
                        "delta": {"cost_usd": 1.25, "tokens_input": 100},
                    }],
                }],
            },
            ("$1.25", "$2.50"),
        ),
        (
            "range-cost",
            ["range-cost", "--start", "2026-07-01T00:00:00Z", "--end", "2026-07-02T00:00:00Z"],
            "_cmd_range_cost_claude",
            {
                "start": "2026-07-01T00:00:00Z",
                "end": "2026-07-02T00:00:00Z",
                "matchedEntries": 1,
                "totalCostUSD": 1.25,
                "modelBreakdowns": [{"model": "claude-test", "totalTokens": 123, "costUSD": 1.25}],
            },
            ("claude-test", "123", "$1.25"),
        ),
        (
            "cache-report",
            ["cache-report", "--since", "2026-07-01", "--until", "2026-07-02"],
            "_cmd_cache_report_claude",
            {
                "days": [{"date": "2026-07-01", "cacheHitPercent": 75.0, "cost": 1.25}],
                "totals": {"totalTokens": 123, "cost": 1.25},
            },
            ("2026-07-01", "75.0%", "$1.25"),
        ),
    ],
)
def test_default_claude_share_uses_structured_legacy_adapter(
    monkeypatch, fmt, command, argv, handler_name, payload, expected,
):
    """The newly-shareable Claude commands must not capture terminal bytes."""
    ns, ls, _source = _kernel()
    emitted = []

    def legacy_handler(args):
        assert args.source == "claude"
        assert args.format is None
        assert args.json is True
        args._source_result_sink(payload)
        return 0

    monkeypatch.setitem(ns, handler_name, legacy_handler)
    monkeypatch.setitem(ns, "_share_render_and_emit", lambda snap, _args: emitted.append(snap))

    assert ns["main"]([*argv, "--format", fmt, "--output", "-"]) == 0

    assert len(emitted) == 1
    snap = emitted[0]
    assert snap.source == "claude"
    assert snap.source_label == "Claude"
    rendered = ls.render(snap, format=fmt, theme="light", branding=True, reveal_projects=True)
    for value in expected:
        assert value in rendered


@pytest.mark.parametrize(
    ("command", "payload", "expected"),
    [
        (
            "project",
            {
                "rangeStart": "2026-07-01",
                "rangeEnd": "2026-07-02",
                "totals": {"costUsd": 3.0},
                "projects": [{
                    "displayKey": "claude-project",
                    "inputTokens": 10,
                    "outputTokens": 20,
                    "cacheWriteTokens": 30,
                    "cacheReadTokens": 40,
                    "costUsd": 3.0,
                }],
            },
            ("claude-project", "100", "$3.00"),
        ),
        (
            "report",
            {
                "trend": [{
                    "weekStartDate": "2026-07-01",
                    "weeklyPercent": 37.0,
                    "weeklyCostUSD": 3.0,
                    "dollarsPerPercent": 3.0 / 37.0,
                }],
            },
            # #503 S2 D4/F15 — the week cell is full ISO, not `%b %d`.
            ("2026-07-01", "37.0%", "$3.00"),
        ),
    ],
)
def test_claude_legacy_payload_adapters_keep_provider_native_rows(command, payload, expected):
    _ns, ls, source = _kernel()

    snap = source.build_source_share_snapshot(
        command, SourceResult("claude", "ok", payload), reveal_projects=False,
    )

    rendered = ls.render(snap, format="md", theme="light", branding=True, reveal_projects=True)
    for value in expected:
        assert value in rendered


@pytest.mark.parametrize(
    ("handler_name", "command", "view_name"),
    [
        ("cmd_codex_daily", "codex-daily", "build_codex_daily_view"),
        ("cmd_codex_monthly", "codex-monthly", "build_codex_monthly_view"),
        ("cmd_codex_weekly", "codex-weekly", "build_codex_weekly_view"),
        ("cmd_codex_session", "codex-session", "build_codex_session_view"),
    ],
)
def test_codex_reports_render_empty_share_before_legacy_no_data_sentinel(
    monkeypatch, handler_name, command, view_name,
):
    ns, ls, _source = _kernel()
    codex = ns["_cctally_codex"]
    start = datetime(2026, 7, 1, tzinfo=UTC)
    end = datetime(2026, 7, 2, tzinfo=UTC)
    emitted = []
    empty_view = SimpleNamespace(
        rows=(), total_cost_usd=0.0, total_tokens=0,
        total_sessions=0, period_start=start, period_end=end,
        display_tz_label="UTC",
    )
    monkeypatch.setitem(ns, "load_config", lambda *_args: {})
    monkeypatch.setitem(ns, "resolve_display_tz", lambda *_args: None)
    monkeypatch.setitem(ns, "_parse_cli_date_range", lambda *_args, **_kwargs: (start, end))
    monkeypatch.setitem(ns, "get_codex_entries", lambda *_args: [])
    monkeypatch.setitem(ns, view_name, lambda *_args, **_kwargs: empty_view)
    monkeypatch.setitem(ns, "get_week_start_name", lambda *_args: "monday")
    monkeypatch.setitem(ns, "_share_render_and_emit", lambda snap, _args: emitted.append(snap))
    monkeypatch.setitem(ns, "_emit_codex_no_data", lambda *_args: pytest.fail("legacy sentinel ran"))
    args = SimpleNamespace(
        config=None, tz=None, timezone=None, compact=False, speed="auto",
        order="asc", breakdown=False, json=False, format="md", theme="light",
        no_branding=False, reveal_projects=False, output="-", copy=False,
        open_after_write=False,
    )

    assert getattr(codex, handler_name)(args) == 0

    assert len(emitted) == 1
    snap = emitted[0]
    assert snap.source == "codex"
    assert snap.source_label == "Codex"
    assert snap.availability == "empty"
    for fmt in ("md", "html", "svg"):
        rendered = ls.render(snap, format=fmt, theme="light", branding=True, reveal_projects=True)
        assert "Codex" in rendered
        assert "No data" in rendered


def test_source_aware_fixture_builder_has_every_state_format_and_no_canaries(tmp_path):
    root = Path(__file__).resolve().parents[1]
    out = tmp_path / "source-aware"
    builder = root / "bin" / "build-source-aware-fixtures.py"
    builder_ns = runpy.run_path(str(builder))
    builder_source = builder.read_text(encoding="utf-8")

    assert '"/raw-path-canary/source-root-canary"' in builder_source
    assert '"repository-canary/project-canary"' in builder_source
    # The canonical artifacts must exercise public source command routes, not
    # call the source emitter with hand-assembled provider results.
    assert "SOURCE_HANDLERS" in builder_source
    assert "CODEX_REPORT_HANDLERS" in builder_source
    assert "_emit_source_result(" not in builder_source
    assert "def _claude_result(" not in builder_source
    assert "_build_codex_share_snapshot(" not in builder_source

    result = subprocess.run(
        [sys.executable, str(builder), "--out", str(out)],
        text=True, capture_output=True, check=False,
    )

    assert result.returncode == 0, result.stderr
    matrix = builder_ns["CANONICAL_MATRIX"]
    expected = builder_ns["expected_artifact_paths"]()
    actual = {path.relative_to(out) for path in out.rglob("*.golden")}
    assert actual == expected
    assert len(matrix) == 38
    assert len(expected) == 190
    source_commands = {case.command for case in matrix if case.family == "source"}
    assert source_commands == {"project", "diff", "range-cost", "cache-report", "report"}
    codex_commands = {case.command for case in matrix if case.family == "codex-report"}
    assert codex_commands == {"codex-daily", "codex-monthly", "codex-weekly", "codex-session"}
    rendered = "\n".join(path.read_text(encoding="utf-8") for path in out.rglob("*.golden"))
    for canary in builder_ns["CANARIES"]:
        assert canary not in rendered

    # Diff goldens are semantic acceptance artifacts, not merely a file-count
    # matrix: every format must preserve the two-window compatible quantities
    # plus representative native row identities/statuses.
    for case in ("source-diff-codex-populated", "source-diff-all-claude-empty"):
        for fmt in ("md", "html", "svg", "terminal"):
            artifact = (out / case / f"output.{fmt}.golden").read_text(encoding="utf-8")
            expected = (
                ("A $", "B $", "Δ", "tokens", "gpt-5", "project", "changed", "new")
                if fmt == "terminal" else
                (("A $", "B $", "Δ $", "Cost", "A", "B", "Δ", "Tokens",
                  "gpt-5", "project-", "changed", "new") if fmt == "svg" else
                 ("A $ Cost", "B $ Cost", "Δ $ Cost", "A Tokens", "B Tokens", "Δ Tokens",
                  "gpt-5", "project-1", "changed", "new"))
            )
            for text in expected:
                assert text in artifact


def test_source_aware_fixture_builder_uses_real_legacy_handlers_and_payloads(tmp_path):
    """All-source artifacts retain handler-produced Claude JSON, not a stub."""
    root = Path(__file__).resolve().parents[1]
    builder = root / "bin" / "build-source-aware-fixtures.py"
    builder_source = builder.read_text(encoding="utf-8")

    # The builder may replace deterministic data/cache/time dependencies, but
    # it must route through the installed legacy command function and its
    # structured-result sink.  A hand-built JSON payload or handler-shaped
    # stub makes the source-aware artifacts stop testing the command boundary.
    assert "def _legacy_payload(" not in builder_source
    assert "def legacy_handler(" not in builder_source
    assert "setattr(module, legacy_handler_name" not in builder_source
    assert "LEGACY_HANDLER_TARGETS" in builder_source

    out = tmp_path / "source-aware"
    result = subprocess.run(
        [sys.executable, str(builder), "--out", str(out)],
        text=True, capture_output=True, check=False,
    )
    assert result.returncode == 0, result.stderr

    for command in ("project", "diff", "range-cost", "cache-report", "report"):
        case_dir = f"source-{command}-all-codex-empty"
        for fmt in ("md", "html", "svg", "terminal", "json"):
            generated = out / case_dir / f"output.{fmt}.golden"
            committed = root / "tests" / "fixtures" / "source-aware" / generated.relative_to(out)
            assert generated.read_bytes() == committed.read_bytes()
        claude = json.loads((out / case_dir / "output.json.golden").read_text(encoding="utf-8"))["sources"][0]
        payload = claude["data"]
        assert claude["source"] == "claude"
        assert claude["status"] == "ok"
        if command == "project":
            assert payload["projects"][0]["inputTokens"] > 0
            assert payload["totals"]["costUsd"] > 0
        elif command == "diff":
            overall = payload["sections"][0]["rows"][0]
            assert overall["a"]["cost_usd"] > 0
            assert overall["b"]["cost_usd"] > 0
        elif command == "range-cost":
            assert payload["modelBreakdowns"][0]["totalTokens"] > 0
            assert payload["totalCostUSD"] > 0
        elif command == "cache-report":
            assert payload["days"][0]["totalTokens"] > 0
            assert payload["totals"]["cost"] > 0
        else:
            assert payload["trend"][0]["weeklyPercent"] > 0
            assert payload["trend"][0]["weeklyCostUSD"] > 0


def test_source_aware_codex_report_goldens_are_plain_under_ci_color_env(tmp_path):
    """Codex-report terminal goldens must stay ANSI-free even when the ambient
    environment forces color. GitHub Actions sets $CI, which
    _supports_color_stdout() treats as color-on; the Codex-report handlers take
    no color arg (unlike the source-family), so the builder must neutralize
    color itself. Without that, the committed plain goldens diverge on CI —
    the exact regression this guards. Non-vacuous: building under CI=1/
    FORCE_COLOR=1 without the NO_COLOR pin re-introduces the \\x1b codes and
    fails the byte-compare below.
    """
    root = Path(__file__).resolve().parents[1]
    builder = root / "bin" / "build-source-aware-fixtures.py"
    out = tmp_path / "source-aware"

    env = {**os.environ, "CI": "1", "FORCE_COLOR": "1"}
    result = subprocess.run(
        [sys.executable, str(builder), "--out", str(out)],
        text=True, capture_output=True, check=False, env=env,
    )
    assert result.returncode == 0, result.stderr

    committed = root / "tests" / "fixtures" / "source-aware"
    for command in ("codex-daily", "codex-monthly", "codex-weekly", "codex-session"):
        rel = Path(f"codex-report-{command}-populated") / "output.terminal.golden"
        generated = (out / rel).read_bytes()
        assert b"\x1b" not in generated, f"{rel} gained ANSI codes under CI color env"
        assert generated == (committed / rel).read_bytes(), rel


def test_source_aware_harness_diffs_committed_artifacts_and_scans_canaries():
    root = Path(__file__).resolve().parents[1]
    harness = root / "bin" / "cctally-source-aware-test"
    harness_source = harness.read_text(encoding="utf-8")

    assert "--manifest" in harness_source
    assert "--canaries" in harness_source

    result = subprocess.run(
        [str(harness)], text=True, capture_output=True, check=False,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "passed: 190   failed: 0" in result.stdout


def _canaries() -> list[str]:
    """The canaries the builder declares, in the order the harness scans them.

    Read from the builder rather than hard-coded, so adding a canary does not
    silently narrow a case that counts one refusal per canary.
    """
    root = Path(__file__).resolve().parents[1]
    listed = subprocess.run(
        [sys.executable, str(root / "bin" / "build-source-aware-fixtures.py"),
         "--canaries"],
        text=True, capture_output=True, check=True,
    ).stdout.splitlines()
    canaries = [line for line in listed if line.strip()]
    assert canaries, "the builder declared no canary"
    return canaries


def _canary_count() -> int:
    return len(_canaries())


def test_the_privacy_canary_fails_when_its_scanner_is_unavailable(tmp_path):
    """A canary that cannot scan must not report a clean scan (#711).

    The harness gated the canary leg on `if rg …` with no availability check,
    and the runners do not carry `rg`, so the leg reported success without ever
    looking at an artifact. `command -v` answers the wrong question — a present
    binary can still be broken — so the harness self-tests the scanner and
    treats every status other than "match" and "clean" as a refusal.

    The fake `grep` is PREPENDED to the child's existing PATH rather than
    replacing it, and this is the whole design of the reproduction: with a
    replaced PATH the harness would fail for want of `python3`, `find` or `wc`
    and the assertion would pass while proving nothing about the scanner. That
    vacuity is the same defect class the test exists to close.
    """
    root = Path(__file__).resolve().parents[1]
    shadow = tmp_path / "shadow-bin"
    shadow.mkdir()
    fake = shadow / "grep"
    fake.write_text("#!/bin/sh\nexit 127\n", encoding="utf-8")
    fake.chmod(0o755)

    env = dict(os.environ)
    env["PATH"] = f"{shadow}{os.pathsep}{env['PATH']}"
    result = subprocess.run(
        [str(root / "bin" / "cctally-source-aware-test")],
        text=True, capture_output=True, check=False, env=env,
    )

    combined = result.stdout + result.stderr
    assert result.returncode != 0, (
        "the harness passed with an unusable scanner, so its privacy leg "
        f"reported a clean scan it never performed:\n{combined}")
    # The PINNED line, not the word "scanner". Both the human-readable sentence
    # and the evidence-retention line carry that word, so deleting the pinned
    # line outright would have left this case green while removing the one
    # sentence an aggregated export can carry.
    assert (
        "FAIL source-aware: privacy scanner failure status=127 phase=self-test "
        "canary=0/0"
    ) in result.stdout, result.stdout


def test_a_silent_scanner_failure_prints_no_bare_blank_line(tmp_path):
    """A scanner can fail with a status and no message.

    `grep` exits 2 for an unreadable path without necessarily writing to
    stderr, and the harness printed its captured output unconditionally, so the
    refusal was followed by an empty line that reads as a truncated report. The
    fake scanner here answers the self-test correctly and fails ONLY the
    recursive canary scan, which is what isolates the reporting path from the
    availability path the case above covers.
    """
    real_grep = shutil.which("grep")
    assert real_grep, "no grep on PATH, so this case cannot build its fake"
    root = Path(__file__).resolve().parents[1]
    shadow = tmp_path / "shadow-bin"
    shadow.mkdir()
    fake = shadow / "grep"
    fake.write_text(
        "#!/bin/sh\n"
        'if [ "$1" = "-R" ]; then exit 2; fi\n'
        f'exec {real_grep} "$@"\n',
        encoding="utf-8",
    )
    fake.chmod(0o755)

    env = dict(os.environ)
    env["PATH"] = f"{shadow}{os.pathsep}{env['PATH']}"
    result = subprocess.run(
        [str(root / "bin" / "cctally-source-aware-test")],
        text=True, capture_output=True, check=False, env=env,
    )

    assert result.returncode != 0, (
        "the harness passed while its scanner refused every canary scan:\n"
        + result.stdout + result.stderr)
    lines = result.stdout.splitlines()
    # #754 pinned the refusal's wording so the aggregator's closed vocabulary
    # can carry it intact. The line names a status, a phase and an ordinal; the
    # scanner's own output moved to the private raw log, which is what removes
    # the bare-blank-line class rather than merely guarding against it.
    refusals = [
        i
        for i, line in enumerate(lines)
        if line.startswith(
            "FAIL source-aware: privacy scanner failure status=2 phase=artifact-scan canary="
        )
    ]
    assert len(refusals) == _canary_count(), result.stdout
    for index in refusals:
        assert not lines[index + 1:] or lines[index + 1] != "", (
            "the refusal is followed by a bare blank line, so the report "
            "looks truncated:\n" + result.stdout)


def _harness_statements(function_name: str) -> list[str]:
    """The statements of one harness function, with continuations joined.

    Returns the shell statements of `function_name` in source order, comments
    and blank lines removed, so a case can make an assertion about the shape of
    a single construct rather than about the whole file.
    """
    root = Path(__file__).resolve().parents[1]
    source = (root / "bin" / "cctally-source-aware-test").read_text(encoding="utf-8")
    start = source.index(f"{function_name}()")
    body = source[start:]
    body = body[: body.index("\n}\n")]
    statements: list[str] = []
    pending = ""
    for raw in body.splitlines():
        stripped = raw.strip()
        if stripped.endswith("\\"):
            pending += stripped[:-1].rstrip() + " "
            continue
        statements.append((pending + stripped).strip())
        pending = ""
    if pending:
        statements.append(pending.strip())
    return [line for line in statements if line and not line.startswith("#")]


def test_the_scan_observes_its_status_without_forking_a_subshell():
    """#760. The scan must not be routed through a command substitution.

    `out=$(… )` forks a bash subshell, and a subshell that dies on a signal
    sets `$?` to 128+N. The harness then recorded that number as the scanner's
    exit status, with the scanner's absolute path and version string attached,
    for a program that may have completed normally. The proof that the number
    was never the scanner's is #766's stand-in: a two-line `/bin/sh` script
    that exits 2 on `-R` before opening any file was still recorded as
    `status=139 signal=11`, and a program that does no work cannot crash from
    the amount of work.

    Reading the source is crude, but it pins the construct on every run. The
    behavioural case below observes the consequence, and the two together are
    what make a green run mean something: the interpreter fault that produced
    the false status is intermittent, so a behavioural case alone would pass
    against the broken construct most of the time.
    """
    statements = _harness_statements("_scan_for_canary")
    invocations = [
        line
        for line in statements
        if "LC_ALL=C" in line and '"$SCANNER_PATH"' in line
    ]
    assert len(invocations) == 1, statements
    invocation = invocations[0]

    assert "$(" not in invocation, (
        "the scan is wrapped in a command substitution, so the status the "
        f"harness reports is a forked subshell's:\n{invocation}")
    assert "`" not in invocation, (
        "the scan is wrapped in a backtick substitution, so the status the "
        f"harness reports is a forked subshell's:\n{invocation}")
    assert "|" not in invocation, (
        "the scan is a pipeline, so the status the harness reports is not "
        f"observed directly from the scanner:\n{invocation}")
    assert invocation.startswith("LC_ALL=C "), (
        "the scan is not the statement's own command, so its status is not "
        f"the scanner's:\n{invocation}")
    assert ">" in invocation, (
        "the scan does not redirect its output to a file, so the harness "
        f"cannot both observe the status directly and keep the output:\n{invocation}")

    index = statements.index(invocation)
    assert statements[index + 1] == "rc=$?", (
        "another statement runs between the scan and the status it records, "
        f"so `$?` is that statement's:\n{statements[index:index + 3]}")


def test_the_reported_scan_status_is_the_status_the_scanner_exited_with(tmp_path):
    """#760. The reported status must be the named program's own.

    WHAT THE STAND-IN ACTUALLY DISCRIMINATES, measured rather than assumed: it
    reports what kind of FILE its own standard output is, and nothing else. A
    direct invocation redirected to a file leaves it writing to a regular file,
    so it exits 3. Both `out=$(…)` and a pipeline leave it writing to a pipe, so
    it exits 4 in either shape, and the harness runs `set -uo pipefail`, which
    reports the status of the LAST command in the pipeline to exit non-zero
    rather than the last element's 0. Measured under those options,
    `( exit 4 ) | cat` reports 4 and `( exit 4 ) | head -1` reports 4, because
    the right-hand stage exits 0 in both; `( exit 4 ) | ( exit 5 )` reports 5,
    which is what "last non-zero" means. Only `set +o pipefail` reports 0.

    So this case cannot tell a command substitution from a pipeline: both
    report 4. It distinguishes each of them from a direct invocation's 3, which
    is the discrimination it exists to make.

    That is still narrower than "direct invocation versus forked subshell".
    `( direct > file ); rc=$?` — a forked subshell that still redirects, and
    still the #760 defect — leaves the stand-in writing to a regular file, so it
    reports 3 and PASSES this case. That shape is covered by
    `test_the_scan_observes_its_status_without_forking_a_subshell`, which reads
    the construct out of the harness source rather than inferring it from a
    status. Neither case covers the other, and both are kept.

    The stand-in also writes a line to standard output before exiting, so the
    case additionally proves the harness still records the scanner's output and
    its byte counts once that output is read from a file rather than captured.
    """
    real_grep = shutil.which("grep")
    assert real_grep, "no grep on PATH, so this case cannot build its stand-in"
    root = Path(__file__).resolve().parents[1]
    shadow = tmp_path / "shadow-bin"
    shadow.mkdir()
    fake = shadow / "grep"
    fake.write_text(
        "#!/bin/sh\n"
        'if [ "$1" = "-R" ]; then\n'
        "    printf 'probe-stdout-line\\n'\n"
        '    if [ -f /dev/stdout ]; then printf "stdout=regular-file\\n" >&2; exit 3; fi\n'
        '    if [ -p /dev/stdout ]; then printf "stdout=pipe\\n" >&2; exit 4; fi\n'
        '    printf "stdout=other\\n" >&2\n'
        "    exit 5\n"
        "fi\n"
        f'exec {real_grep} "$@"\n',
        encoding="utf-8",
    )
    fake.chmod(0o755)

    retained_dir = tmp_path / "retained"
    env = dict(os.environ)
    env["PATH"] = f"{shadow}{os.pathsep}{env['PATH']}"
    env["CCTALLY_SOURCE_AWARE_RAW_LOG_DIR"] = str(retained_dir)
    result = subprocess.run(
        [str(root / "bin" / "cctally-source-aware-test")],
        text=True, capture_output=True, check=False, env=env,
    )

    assert result.returncode != 0, (
        "the harness passed while its scanner refused every canary scan:\n"
        + result.stdout + result.stderr)
    prefix = "FAIL source-aware: privacy scanner failure status="
    statuses = [
        line[len(prefix):].split(None, 1)[0]
        for line in result.stdout.splitlines()
        if line.startswith(prefix)
    ]
    assert statuses.count("3") == _canary_count(), (
        "the harness did not report the stand-in's own exit status for every "
        f"canary; it reported {statuses}. A `4` means the scanner's output "
        "went to a pipe, so the scan was routed through a command substitution "
        f"or a pipeline rather than invoked directly:\n{result.stdout}")
    assert set(statuses) == {"3"}, result.stdout

    retained = sorted(retained_dir.glob("scanner-raw.*.log"))
    assert retained, sorted(p.name for p in retained_dir.iterdir())
    raw = retained[-1].read_text(encoding="utf-8")
    # Every diagnostic field the retained log carried before the fix is still
    # written, and the output one now comes from the file.
    assert "scan ordinal=1/" in raw, raw
    # SCOPED TO THE SCAN RECORD. `_resolve_scanner` writes its own
    # `resolve executable=…` and `  version=…` lines on every successful run,
    # so an unscoped `in raw` is satisfied by resolution alone: both assertions
    # would still pass if `_scan_for_canary` dropped both of its own lines, and
    # the fields this case exists to pin would be gone with the case green.
    scan_record = raw[raw.index("scan ordinal=1/"):]
    assert f"executable={shadow}/grep" in scan_record, raw
    assert "version=" in scan_record, raw
    assert "argv=" in raw, raw
    assert "started=" in raw and "ended=" in raw, raw
    assert "scanner-stdout: probe-stdout-line" in raw, raw
    assert "scanner-stderr: stdout=regular-file" in raw, raw
    assert "stdout_bytes=0" not in raw, (
        "the harness recorded no bytes for output the scanner did write, so "
        f"the byte count is not read from the output file:\n{raw}")


def test_the_scanner_is_resolved_without_forking_a_subshell():
    """#769 S1 round 3. The same construct class, one function over.

    `_resolve_scanner` read `command -v grep` through a command substitution and
    consumed its status with `||`. A subshell dying from the #776 interpreter
    fault would therefore have made the harness announce that no absolute path
    for the scanner could be resolved, on a machine where `grep` is present —
    a false diagnosis on a status-reporting path, which is exactly #760's class.
    It is less severe only because the status it publishes is a hardcoded 127
    rather than the subshell's own number.

    The version capture is included in the rule rather than exempted from it. A
    rule scoped to the one statement whose status is consumed is satisfied by
    re-introducing a substitution on the line beside it, and the replacement is
    strictly simpler anyway: a redirect plus a `read` builtin removes both the
    forked subshell and the `head` process while preserving first-line
    semantics exactly.
    """
    statements = _harness_statements("_resolve_scanner")
    # The non-emptiness guard its sibling gets from `len(invocations) == 1`.
    # `offenders == []` over an empty statement list is vacuously true, so an
    # extractor that stopped finding this function's body — a renamed function,
    # a changed brace style — would leave this case green while checking
    # nothing at all.
    assert statements, (
        "the extractor returned no statements for _resolve_scanner, so the "
        "assertion below would pass over an empty list")
    assert any(line.startswith("command -v grep") for line in statements), (
        "the extracted statements do not contain the resolution this case is "
        f"about, so it is reading the wrong body:\n{statements}")
    offenders = [
        line for line in statements if "$(" in line or "`" in line
    ]
    assert offenders == [], (
        "the scanner resolution reads a value through a command substitution, "
        "so a subshell that dies takes the harness's diagnosis with it:\n"
        + "\n".join(offenders))


_GOLDEN_DIFF_HEADER_RE = re.compile(
    r"^FAIL [^:]+: .+ diverged(?: \(diff error rc=.*\))?$"
)
# The five line shapes `diff -u` emits: the two file headers, a hunk header, a
# context/removed/added line, and the no-final-newline note.
_UNIFIED_DIFF_LINE_RE = re.compile(r"^(?:--- |\+\+\+ |@@ |[-+ ]|\\ )")


def _golden_diff_body_indices(lines: list[str]) -> set[int]:
    """Indices of the unified-diff lines `bin/_lib-golden-diff.sh` printed.

    `_golden_diff_files` prints `FAIL <name>: <label> diverged` and then pipes
    the whole unified diff through `head`, so its body is the run of
    diff-shaped lines that follows such a header. Identifying the body by that
    SHAPE is what lets a caller exclude it structurally instead of by guessing
    which lines might contain a needle.

    The header itself is deliberately NOT part of the body. It is built from a
    scenario name and a relative artifact path, so it cannot carry a canary,
    and leaving it in the checked set keeps the exclusion as narrow as the
    reason for it.
    """
    body: set[int] = set()
    inside = False
    for index, line in enumerate(lines):
        if _GOLDEN_DIFF_HEADER_RE.match(line):
            inside = True
            continue
        if inside and _UNIFIED_DIFF_LINE_RE.match(line):
            body.add(index)
            continue
        inside = False
    return body


# The six canaries the planted-artifact case drives, one parametrized case
# each. `test_every_declared_canary_has_a_planted_case` asserts this list is
# the builder's declared set, so a seventh canary fails the suite until its
# case exists rather than going silently uncovered.
_PLANTED_CANARIES = [
    "/raw-path-canary", "source-root-canary", "conversation-canary",
    "quota-canary", "repository-canary", "project-canary",
]


def test_every_declared_canary_has_a_planted_case():
    """The parametrize list above must BE the builder's canary set.

    A canary the builder stops declaring already fails loudly, through the
    `canary in declared` assertion inside the planted case. A canary the
    builder STARTS declaring failed nothing: the parametrize list is a literal,
    so the new canary simply never got an end-to-end case, and the only leg
    that proves the harness reads the corpus it certifies would have covered
    six of seven.
    """
    declared = _canaries()
    assert set(_PLANTED_CANARIES) == set(declared), (
        "the planted-canary parametrize list and the builder's declared "
        f"canaries differ; declared={declared}, parametrized={_PLANTED_CANARIES}")
    assert len(_PLANTED_CANARIES) == len(set(_PLANTED_CANARIES)), _PLANTED_CANARIES


@pytest.mark.parametrize("canary", _PLANTED_CANARIES)
def test_the_real_harness_scan_path_finds_a_planted_canary(tmp_path, canary):
    """Plant a canary in a generated artifact; the HARNESS must catch it.

    Not the scanner's own self-test — the production traversal, over the real
    generated corpus, reached the way the harness reaches it.

    THE ONLY CASE THAT FAILS ON A SCAN THAT READS NOTHING. The fixture corpus
    deliberately carries no canary, so every canary scan is expected to find
    nothing, and a scanner that traverses the whole corpus and one that
    traverses none of it produce the same six clean statuses. Every other case
    in this file, and the whole campaign behind #760, is satisfied by either.

    The canary goes at the END of the LAST artifact in sorted order, so a scan
    that stops early — at a file count, a byte budget, or the first directory —
    misses it and this case fails.
    """
    root = Path(__file__).resolve().parents[1]
    declared = _canaries()
    assert canary in declared, (
        f"{canary!r} is not one of the builder's canaries: {declared}")
    artifacts = tmp_path / "artifacts"
    subprocess.run(
        [sys.executable, str(root / "bin" / "build-source-aware-fixtures.py"),
         "--out", str(artifacts)],
        text=True, capture_output=True, check=True,
    )
    victim = sorted(artifacts.rglob("*.golden"))[-1]
    victim.write_bytes(victim.read_bytes() + canary.encode("utf-8") + b"\n")

    env = dict(os.environ)
    env["CCTALLY_TESTING"] = "1"
    env["CCTALLY_SOURCE_AWARE_PLANTED_ARTIFACTS"] = str(artifacts)
    # Kept out of the shared default directory, which two sibling cases already
    # write to and clean up by name.
    env["CCTALLY_SOURCE_AWARE_RAW_LOG_DIR"] = str(tmp_path / "retained")
    result = subprocess.run(
        [str(root / "bin" / "cctally-source-aware-test")],
        text=True, capture_output=True, check=False, env=env,
    )

    assert result.returncode != 0, (
        f"the harness reported clean with {canary!r} planted at the end of "
        f"{victim.name}, so its privacy leg does not read the corpus it "
        "certifies:\n" + result.stdout + result.stderr)
    ordinal = declared.index(canary) + 1
    assert (
        f"FAIL source-aware: privacy canary match canary={ordinal}/"
        f"{len(declared)}"
    ) in result.stdout, result.stdout
    # The canary VALUE stays private even when it is the thing that was found.
    #
    # Planting a canary also makes that artifact diverge from its committed
    # golden, so the golden-diff leg prints the differing line with the canary
    # in it. That reprint is EXCLUDED STRUCTURALLY — by the shape of the lines
    # `_golden_diff_files` emits — and every other line of stdout is required to
    # be free of the canary, the privacy leg's own lines included.
    #
    # The previous form filtered stdout down to lines beginning
    # `FAIL source-aware:` or `source-aware:`. Both of those shapes are built
    # from an ordinal and a status and cannot contain a canary whatever the
    # harness does, so the assertion could only fire if someone edited the
    # `privacy canary match` echo to interpolate the canary. It was therefore
    # blind to the regression the harness comment says was removed: an
    # unconditional `printf '%s\n' "$out"` reprinting the scanner's matched
    # line, which publishes both the canary and the artifact path. The
    # measurement that showed this: the canary DOES reach stdout on exactly one
    # line, `+/raw-path-canary`, and that line starts with `+`, so the filter
    # skipped it.
    #
    # `test_the_private_log_retains_what_the_public_line_omits` does not cover
    # the reprint either, because its stand-in exits 139 before matching
    # anything, so there is no matched line to reprint.
    lines = result.stdout.splitlines()
    diff_body = _golden_diff_body_indices(lines)
    leaked = [
        line for index, line in enumerate(lines)
        if index not in diff_body and canary in line
    ]
    assert leaked == [], (
        "the canary value reached a line outside the golden diff's body, so a "
        f"public line published the needle the leg exists to hide:\n{leaked}")


def test_the_planted_artifact_hook_is_inert_without_cctally_testing(tmp_path):
    """The hook redirects the scan away from the corpus the harness certifies.

    An operator with a stray export would otherwise get a green authoritative
    run over whatever tree that variable happened to name. The second condition
    is what keeps the hook a test seam rather than an override.
    """
    root = Path(__file__).resolve().parents[1]
    empty = tmp_path / "empty-tree"
    empty.mkdir()

    env = dict(os.environ)
    env.pop("CCTALLY_TESTING", None)
    env["CCTALLY_SOURCE_AWARE_PLANTED_ARTIFACTS"] = str(empty)
    # As the two sibling planted-hook cases do. Setting the directory also sets
    # the harness's RAW_LOG_ALWAYS, so this run retains its log unconditionally
    # rather than only on failure — into this case's own temporary directory.
    # Without it the retention would land in the shared default inside the
    # repository, `$REPO_ROOT/.cctally-remote-state/source-aware-evidence/`.
    env["CCTALLY_SOURCE_AWARE_RAW_LOG_DIR"] = str(tmp_path / "retained")
    result = subprocess.run(
        [str(root / "bin" / "cctally-source-aware-test")],
        text=True, capture_output=True, check=False, env=env,
    )

    assert result.returncode == 0, (
        "the harness honoured the planted-artifact hook without "
        "CCTALLY_TESTING=1, so an exported variable can redirect an "
        "authoritative run:\n" + result.stdout + result.stderr)
    assert "passed: 190   failed: 0" in result.stdout, result.stdout


def test_the_planted_artifact_hook_refuses_a_root_outside_the_temporary_tree(tmp_path):
    """The bound `stage_fixtures_out_of_tree` has, on the one hook that lacked it.

    The hook is read-only, so the worst case today is a recursive scan of
    whatever tree it names — and the tree it is most likely to name by accident
    is the committed fixture tree, which makes every comparison pass because the
    generated side and the golden side are then the same file. The refusal is
    the same three-arm `$TMPDIR` case the staging helper uses, `/private`
    included, because macOS resolves the temporary root through it.
    """
    root = Path(__file__).resolve().parents[1]
    inside_the_repo = root / "tests" / "fixtures" / "source-aware"

    env = dict(os.environ)
    env["CCTALLY_TESTING"] = "1"
    env["CCTALLY_SOURCE_AWARE_PLANTED_ARTIFACTS"] = str(inside_the_repo)
    env["CCTALLY_SOURCE_AWARE_RAW_LOG_DIR"] = str(tmp_path / "retained")
    result = subprocess.run(
        [str(root / "bin" / "cctally-source-aware-test")],
        text=True, capture_output=True, check=False, env=env,
    )

    assert result.returncode != 0, (
        "the harness accepted a planted-artifact root inside the repository, so "
        "the hook can point the scan at any tree on the machine:\n"
        + result.stdout + result.stderr)
    assert (
        "FAIL source-aware: artifact path not under tmpdir "
    ) in result.stdout, result.stdout


# --- #784: builder attribution and physical containment ---------------------
#
# The four refusals below must hold under BOTH interpreters this repository
# runs bash from, so their bodies live in `tests/_source_aware_bash_refusals`
# and each module calls them under one interpreter. This module is PUBLIC and
# runs them under `/bin/bash`, the only interpreter a public clone is
# guaranteed to have; the Homebrew 5.x leg is the mirror-private twin
# `tests/test_source_aware_share_homebrew_bash.py`. Both keep static node ids
# and neither introduces a suppression.

from _source_aware_bash_refusals import (  # noqa: E402
    BLANK_CANARY_BODIES,
    FLOOR_BASH,
    builder_shim_farm,
    check_a_blank_canary_is_refused_and_one_nonblank_is_required,
    check_a_crashed_manifest_builder_is_reported_as_a_builder_failure,
    check_the_planted_hook_refuses_a_symlink_out_of_the_temporary_root,
    check_the_planted_hook_refuses_a_traversal_out_of_the_temporary_root,
)


def _canary_shim_farm(tmp_path, root: Path, canaries_body: str) -> Path:
    """The `--canaries` form of `builder_shim_farm`, kept for its three callers."""
    return builder_shim_farm(tmp_path, root, canaries_body=canaries_body)


def test_a_canary_list_that_scans_nothing_is_refused(tmp_path):
    """A leg that reports success while having verified nothing.

    When `--canaries` prints nothing the scan loop runs zero times, and the
    harness prints `passed: 190   failed: 0` and exits 0 without having scanned
    for a single canary. That is #711's defect family exactly, and the corpus
    cannot expose it: every artifact is clean by construction, so a scan that
    found nothing and a scan that never happened produce identical output.

    The expected-paths leg already cross-checks its own count against `find`.
    This is the counterpart the canary list never had.

    The builder here SUCCEEDS and prints nothing, which is the declaration
    refusal; the case below covers a builder that dies while printing nothing,
    and each asserts the other's line is absent, because reporting one as the
    other names a cause the harness never observed.
    """
    root = Path(__file__).resolve().parents[1]
    farm = _canary_shim_farm(tmp_path, root, "    raise SystemExit(0)")

    env = dict(os.environ)
    env["CCTALLY_SOURCE_AWARE_RAW_LOG_DIR"] = str(tmp_path / "retained")
    result = subprocess.run(
        [str(farm / "bin" / "cctally-source-aware-test")],
        text=True, capture_output=True, check=False, env=env,
    )

    assert result.returncode != 0, (
        "the harness passed with an empty canary list, so it reported a clean "
        "privacy scan it never performed:\n" + result.stdout + result.stderr)
    assert (
        "FAIL source-aware: privacy canary count expected at least 1, actual 0"
    ) in result.stdout, result.stdout
    assert "privacy canary builder exit status" not in result.stdout, (
        "a builder that succeeded and declared nothing was reported as a "
        "builder failure:\n" + result.stdout)
    # The refusal takes the same path the other three do, so it says where the
    # evidence went rather than leaving the reader to guess.
    assert "source-aware: scanner evidence retained at " in result.stdout, result.stdout


def test_a_crashed_canary_builder_is_not_reported_as_an_empty_declaration(tmp_path):
    """A cause the harness did not observe — #760's class, one leg over.

    The process substitution that fed `canaries` published no status, so a
    `--canaries` invocation that DIED while printing nothing produced an empty
    list and the harness announced that the fixture builder had declared no
    privacy canary. Fail-closed, and a false statement about what happened: the
    builder declared nothing because it never got that far.

    The shim exits 3 on `--canaries` and writes nothing, and delegates every
    other invocation to the real builder, so the crash is the only thing under
    test.
    """
    root = Path(__file__).resolve().parents[1]
    farm = _canary_shim_farm(tmp_path, root, "    raise SystemExit(3)")

    env = dict(os.environ)
    env["CCTALLY_SOURCE_AWARE_RAW_LOG_DIR"] = str(tmp_path / "retained")
    result = subprocess.run(
        [str(farm / "bin" / "cctally-source-aware-test")],
        text=True, capture_output=True, check=False, env=env,
    )

    assert result.returncode != 0, (
        "the harness passed with a canary builder that crashed:\n"
        + result.stdout + result.stderr)
    assert (
        "FAIL source-aware: privacy canary builder exit status 3"
    ) in result.stdout, result.stdout
    assert "privacy canary count expected" not in result.stdout, (
        "a crashed canary builder was reported as an empty declaration, which "
        "names a cause the harness never observed:\n" + result.stdout)
    assert "source-aware: scanner evidence retained at " in result.stdout, result.stdout


# --- #784: builder attribution and physical containment ---------------------


def test_a_crashed_manifest_builder_is_reported_as_a_builder_failure(tmp_path):
    check_a_crashed_manifest_builder_is_reported_as_a_builder_failure(
        tmp_path, FLOOR_BASH)


def test_the_planted_hook_refuses_a_traversal_out_of_the_temporary_root(tmp_path):
    check_the_planted_hook_refuses_a_traversal_out_of_the_temporary_root(
        tmp_path, FLOOR_BASH)


def test_the_planted_hook_refuses_a_symlink_out_of_the_temporary_root(tmp_path):
    check_the_planted_hook_refuses_a_symlink_out_of_the_temporary_root(
        tmp_path, FLOOR_BASH)


@pytest.mark.parametrize(
    "canaries_body",
    [pytest.param(body, id=name) for name, body in BLANK_CANARY_BODIES],
)
def test_a_blank_canary_is_refused_and_one_nonblank_is_required(
    tmp_path, canaries_body
):
    check_a_blank_canary_is_refused_and_one_nonblank_is_required(
        tmp_path, FLOOR_BASH, canaries_body)


def test_source_aware_fixture_builder_and_harness_are_executable_regular_scripts():
    root = Path(__file__).resolve().parents[1]

    for script in (
        root / "bin" / "build-source-aware-fixtures.py",
        root / "bin" / "cctally-source-aware-test",
    ):
        mode = script.stat().st_mode
        assert stat.S_ISREG(mode), script
        assert mode & (stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH), script


def test_source_aware_harness_uses_bash_3_compatible_read_loops():
    root = Path(__file__).resolve().parents[1]
    harness_source = (root / "bin" / "cctally-source-aware-test").read_text(encoding="utf-8")

    assert "mapfile" not in harness_source
    assert "while IFS= read -r" in harness_source


def test_source_aware_harness_is_a_required_bundle_gate():
    """#529 S1 retired the narrow `required_harnesses` list of #446 Task B: the
    estate manifest now declares EVERY harness and admission requires exact set
    equality in both directions, so this gate is asserted against the manifest
    rather than against a hardcoded shell array."""
    root = Path(__file__).resolve().parents[1]
    bundle = (root / "bin" / "cctally-test-all").read_text(encoding="utf-8")
    manifest = json.loads(
        (root / "tests" / "authoritative-test-manifest.json").read_text(
            encoding="utf-8"
        )
    )
    rows = {row["name"]: row for row in manifest["harnesses"]}

    assert {"codex-quota", "source-aware"} <= set(rows)
    assert rows["codex-quota"]["visibility"] == "public"
    assert rows["source-aware"]["visibility"] == "public"

    # test-remote is maintainer-local and deliberately unmirrored, so it is
    # required only where it is supposed to exist: demanding it unconditionally
    # took every public CI job down on the v1.89.0 snapshot before a single
    # harness ran. Declaring it `private` is what scopes it to the private
    # profile now. The behavioral contract (private tree refuses a missing or
    # non-executable harness; public subset plans cleanly without it) is pinned
    # in tests/test_test_all_scheduler.py; guard the discriminator here so it
    # cannot be dropped back to an unconditional literal unnoticed.
    assert rows["test-remote"]["visibility"] == "private"
    assert '[ -f "$REPO_ROOT/.mirror-allowlist" ]' in bundle
    assert "contract_admit_harnesses" in bundle
    # The retired list must not creep back: two admission mechanisms would
    # disagree the moment one of them was updated alone.
    assert "required_harnesses=(" not in bundle


def _live_release_version(root: Path) -> str:
    """First stamped ``## [x.y.z]`` header in the repo CHANGELOG."""
    for line in (root / "CHANGELOG.md").read_text(encoding="utf-8").splitlines():
        if line.startswith("## [") and "Unreleased" not in line:
            return line.split("[", 1)[1].split("]", 1)[0]
    raise AssertionError("no stamped CHANGELOG version found")


def test_source_aware_branded_goldens_are_version_pinned_not_release_coupled():
    """The branded md/html/svg goldens must embed a fixed stub version, never
    the live CHANGELOG version.

    Regression guard for the v1.69.0 break: the builder read
    ``_release_version()`` (latest CHANGELOG entry) unpinned, so the committed
    goldens froze whatever version was current at generation time and every
    subsequent release re-staled all 74 branded goldens — reddening dev + public
    CI on the release commit itself. The builder now pins a ``9.9.9`` stub
    (bin/build-source-aware-fixtures.py), mirroring the share-v2 harness.

    Non-vacuous: the assertion below fails the instant the pin is removed, since
    the live repo version (1.69.x+) is never ``9.9.9``.
    """
    root = Path(__file__).resolve().parents[1]
    live = _live_release_version(root)
    assert live != "9.9.9", "repo happens to be at the stub version; pick another stub"

    branded = (
        root / "tests" / "fixtures" / "source-aware"
        / "codex-report-codex-daily-populated" / "output.md.golden"
    ).read_text(encoding="utf-8")
    assert "cctally_version: 9.9.9" in branded
    assert f"cctally_version: {live}" not in branded

    # The builder itself must carry the pin so any regeneration self-pins.
    builder_source = (root / "bin" / "build-source-aware-fixtures.py").read_text(encoding="utf-8")
    assert "CCTALLY_TEST_CHANGELOG_PATH" in builder_source
    assert "os.get_terminal_size" in builder_source


# =====================================================================
# #503 S2 Task 11 — exit-3 parity for all-source composition (F19).
#
# Single-source rendering maps `SharePrivacyViolation` to exit 3 and a
# one-line refusal. The all-source path called `compose()` with no such
# catch, so the same refusal fell through to the generic handler in
# `bin/cctally` and exited 1. Documenting exit 3 while one path exits 1
# would leave F19 half-closed.
# =====================================================================

def _clean_codex_report_result():
    at = datetime(2026, 7, 2, 12, tzinfo=UTC)
    return SourceResult("codex", "ok", CodexReportData(
        as_of=at,
        series=(CodexReportSeries(
            quota_key="quota:opaque", slot="five-hour", window_minutes=300,
            rows=(CodexReportRow(
                block_start=datetime(2026, 7, 2, 7, tzinfo=UTC),
                reset_at=at, used_percent=37.0, cost_usd=4.25,
                cost_per_percent=4.25 / 37, status="ok",
            ),),
        ),),
        quota_status="ok",
    ))


def _poisoned_report_result(source: str):
    """A legacy Claude report payload whose week label is an absolute path.

    `_claude_legacy_share_rows` parses `weekStartDate` as a date and, when
    that fails, uses the raw value as the cell text — so this reaches the
    artifact verbatim and trips the detector's absolute-path class. A real
    reproduction through the real compose path, not a monkeypatched raise.
    """
    return SourceResult(source, "ok", {
        "trend": [{
            "weekStartDate": "/Volumes/FIXTURE/repos/sample-project",
            "weeklyPercent": 37.0,
            "weeklyCostUSD": 3.0,
            "dollarsPerPercent": 3.0 / 37.0,
        }],
    })


class _AllSourceArgs:
    source = "all"
    format = "md"
    theme = "light"
    no_branding = False
    reveal_projects = False
    open_after_write = False
    output = "-"
    copy = False
    command = "report"


def test_a_single_source_share_refusal_exits_three():
    ns, _ls, _source = _kernel()

    class _Args(_AllSourceArgs):
        source = "claude"

    with pytest.raises(SystemExit) as exc:
        ns["_cctally_source_analytics"]._emit_source_share(
            _Args(), _poisoned_report_result("claude"),
            command="report", claude=None)
    assert exc.value.code == 3


def test_all_source_share_refusal_exits_three_like_the_single_source_path():
    ns, _ls, _source = _kernel()
    with pytest.raises(SystemExit) as exc:
        ns["_cctally_source_analytics"]._emit_source_share(
            _AllSourceArgs(), _clean_codex_report_result(),
            command="report", claude=_poisoned_report_result("claude"))
    assert exc.value.code == 3


def test_the_all_source_refusal_message_matches_the_single_source_one(capsys):
    ns, _ls, _source = _kernel()
    with pytest.raises(SystemExit):
        ns["_cctally_source_analytics"]._emit_source_share(
            _AllSourceArgs(), _clean_codex_report_result(),
            command="report", claude=_poisoned_report_result("claude"))
    err = capsys.readouterr().err
    assert err.startswith("cctally: refused to write a share artifact"), err
    assert "absolute path" in err


def test_the_all_source_refusal_writes_nothing(tmp_path):
    ns, _ls, _source = _kernel()
    target = tmp_path / "report.md"

    class _Args(_AllSourceArgs):
        output = str(target)

    with pytest.raises(SystemExit):
        ns["_cctally_source_analytics"]._emit_source_share(
            _Args(), _clean_codex_report_result(),
            command="report", claude=_poisoned_report_result("claude"))
    assert not target.exists()


# =====================================================================
# #503 S2 review — F4: the project column's HEADER was being anonymized.
#
# `ColumnSpec(kind="project")` declares that the column's LABEL is a
# project display name, which is true for the cross-tab Detail templates
# whose headers ARE project names. The two `project`-command adapters
# below set it on a column whose label is the literal word `Project`, so
# the anonymizer rewrote the header itself: `source-project-codex-empty`
# rendered `<th>project-1</th>`, and `source-project-all-claude-empty`
# rendered a `<th>project-2</th>` header above a `project-1` data row, so
# the header and the row alias disagreed and the column was unlabelled.
# =====================================================================

def _f4_project_payload() -> dict:
    return {
        "projects": [
            {"displayLabel": "repos/alpha", "project": "repos/alpha",
             "costUsd": 3.0, "inputTokens": 10, "outputTokens": 5},
            {"displayLabel": "repos/beta", "project": "repos/beta",
             "costUsd": 1.0, "inputTokens": 4, "outputTokens": 2},
        ],
    }


def test_the_project_column_header_is_not_a_project_name():
    """The header is chrome, not data; only the CELLS are project names."""
    _ns, ls, analytics = _kernel()
    columns, _rows, _totals = analytics._claude_project_share_rows(
        _f4_project_payload(), ls)
    assert columns[0].label == "Project"
    assert columns[0].kind is None, (
        "the literal header word must not be declared a project display name")


@pytest.mark.parametrize("fmt", ["md", "html", "svg"])
@pytest.mark.parametrize("reveal", [False, True])
def test_a_rendered_project_artifact_keeps_its_column_header(fmt, reveal):
    _ns, ls, analytics = _kernel()
    columns, rows, totals = analytics._claude_project_share_rows(
        _f4_project_payload(), ls)
    snap = ls.ShareSnapshot(
        cmd="project", title="Project Report", subtitle=None,
        period=_period(ls), columns=columns, rows=rows, chart=None,
        totals=totals, notes=(),
        generated_at=datetime(2026, 7, 2, 12, 0, tzinfo=UTC), version="9.9.9",
    )
    out = ls.render(snap, format=fmt, theme="light", branding=True,
                    reveal_projects=reveal)
    import re as _re
    if fmt == "md":
        header = next(line for line in out.splitlines()
                      if line.startswith("| ")).split("|")[1].strip()
    elif fmt == "html":
        header = _re.search(r"<th[^>]*>([^<]*)</th>", out).group(1)
    else:
        # The SVG table's header cells are the bold sans-serif texts.
        header = _re.search(
            r'<text[^>]*font-family="sans-serif"[^>]*font-weight="bold"[^>]*>'
            r'([^<]*)</text>', out).group(1)
    assert header == "Project", (fmt, reveal, header)
    assert not _re.fullmatch(r"project-\d+", header), (fmt, reveal, header)


def test_the_private_log_retains_what_the_public_line_omits(tmp_path):
    """The public line is deliberately thin; the evidence lives in the raw log.

    The shim exits 139 on the recursive scan and delegates everything else to
    the real grep, so the self-test passes and only the artifact scan crashes —
    which is the shape the runners actually produce. `_resolve_scanner` calls
    `command -v grep`, which still honours PATH, so the shim resolves and is
    recorded exactly as a real binary would be.
    """
    real_grep = shutil.which("grep")
    assert real_grep, "no grep on PATH, so this case cannot build its fake"
    root = Path(__file__).resolve().parents[1]
    shadow = tmp_path / "shadow-bin"
    shadow.mkdir()
    fake = shadow / "grep"
    fake.write_text(
        "#!/bin/sh\n"
        'if [ "$1" = "-R" ]; then exit 139; fi\n'
        f'exec {real_grep} "$@"\n',
        encoding="utf-8",
    )
    fake.chmod(0o755)

    retained_dir = tmp_path / "retained"
    env = dict(os.environ)
    env["PATH"] = f"{shadow}{os.pathsep}{env['PATH']}"
    env["CCTALLY_SOURCE_AWARE_RAW_LOG_DIR"] = str(retained_dir)
    result = subprocess.run(
        [str(root / "bin" / "cctally-source-aware-test")],
        text=True, capture_output=True, check=False, env=env,
    )

    assert result.returncode != 0
    assert "privacy scanner failure status=139 phase=artifact-scan" in result.stdout
    assert "/raw-path-canary" not in result.stdout, (
        "a canary value reached public output:\n" + result.stdout)
    assert str(shadow) not in result.stdout, (
        "an absolute path reached public output:\n" + result.stdout)

    # The retained copy is named per invocation rather than `scanner-raw.log`,
    # so a campaign of sequential runs does not overwrite the one run whose
    # evidence it was collected to keep.
    retained = sorted(retained_dir.glob("scanner-raw.*.log"))
    assert retained, sorted(p.name for p in retained_dir.iterdir())
    raw = retained[-1].read_text(encoding="utf-8")
    assert f"executable={shadow}/grep" in raw
    assert "version=" in raw
    assert "argv=" in raw
    assert "signal=11" in raw
    # The resolution attempt is recorded before the program is known, so a run
    # that cannot name its scanner still says it tried.
    assert raw.splitlines()[0].startswith("resolve attempted"), raw.splitlines()[:3]
    # What the public line omits is present here and only here.
    assert "/raw-path-canary" in raw


def _crashing_grep_environment(tmp_path):
    """A PATH whose `grep` crashes the recursive scan and delegates the rest.

    PREPENDED rather than replacing PATH: a replaced PATH would fail the harness
    for want of `python3`, `find` or `wc`, and the case would then pass while
    proving nothing about the scanner.
    """
    real_grep = shutil.which("grep")
    assert real_grep, "no grep on PATH, so this case cannot build its fake"
    shadow = tmp_path / "shadow-bin"
    shadow.mkdir()
    fake = shadow / "grep"
    fake.write_text(
        "#!/bin/sh\n"
        'if [ "$1" = "-R" ]; then exit 139; fi\n'
        f'exec {real_grep} "$@"\n',
        encoding="utf-8",
    )
    fake.chmod(0o755)
    env = dict(os.environ)
    env["PATH"] = f"{shadow}{os.pathsep}{env['PATH']}"
    env.pop("CCTALLY_SOURCE_AWARE_RAW_LOG_DIR", None)
    return env


def test_a_failing_run_retains_its_evidence_with_no_environment_variable_set(tmp_path):
    """The authoritative run is the one that has no variable set.

    Nothing sets `CCTALLY_SOURCE_AWARE_RAW_LOG_DIR` — not `bin/cctally-test-all`,
    not `bin/cctally-test-remote`, not CI — so in the run where the crash under
    investigation actually manifests, the raw log lived only in the scratch
    directory the EXIT trap removes. The public line correctly named a status, a
    phase and an ordinal, and every field that identifies the program was deleted
    microseconds later. Retention is therefore unconditional on a failure, to a
    durable default the wrapper never copies back.
    """
    root = Path(__file__).resolve().parents[1]
    default_dir = root / ".cctally-remote-state" / "source-aware-evidence"

    result = subprocess.run(
        [str(root / "bin" / "cctally-source-aware-test")],
        text=True, capture_output=True, check=False,
        env=_crashing_grep_environment(tmp_path),
    )

    assert result.returncode != 0, result.stdout
    assert "privacy scanner failure status=139 phase=artifact-scan" in result.stdout
    # Identity comes from THIS invocation's own output, never from counting the
    # directory. The retention directory is shared and real, and `pytest -n`
    # runs other cases that invoke this same harness concurrently; their
    # retained logs carry the same `scanner-raw.cctally-source-aware.` prefix,
    # so no glob can separate them from this run's. An earlier form snapshotted
    # the directory before and after and asserted exactly one new file, which
    # failed as `assert 2 == 1` on every `-n 10` run once a sibling case began
    # retaining evidence of its own. The harness prints the path it kept, so
    # that line is the only race-free identity available.
    retained = re.search(
        r"^source-aware: scanner evidence retained at (.+)$",
        result.stdout,
        re.MULTILINE,
    )
    assert retained, result.stdout
    kept = Path(retained.group(1))

    try:
        assert kept.parent == default_dir, kept
        # Named per invocation, so a 300-run campaign cannot overwrite the one
        # crashing run whose evidence it was collected to keep.
        assert kept.name.startswith("scanner-raw.cctally-source-aware."), kept.name
        assert kept.is_file(), kept
        raw = kept.read_text(encoding="utf-8")
        assert "signal=11" in raw
        assert "argv=" in raw
        assert "version=" in raw
    finally:
        # Unlink the one path this run created. The previous form popped the
        # only element out of the set it then iterated in `finally`, so it
        # deleted nothing and every run left a file behind.
        kept.unlink(missing_ok=True)


def test_the_retention_default_is_ignored_by_git(tmp_path):
    """A kept log must never dirty the tree it was produced from.

    `git status --porcelain` staying clean is what keeps a retained log out of a
    staged tree, out of the UI-QA guard's source digest and out of the release
    gate's dirt check.
    """
    root = Path(__file__).resolve().parents[1]
    default_dir = root / ".cctally-remote-state" / "source-aware-evidence"
    default_dir.mkdir(parents=True, exist_ok=True)
    probe = default_dir / "scanner-raw.ignore-probe.log"
    probe.write_text("probe\n", encoding="utf-8")
    try:
        result = subprocess.run(
            ["git", "check-ignore", "-q", str(probe)],
            cwd=root, capture_output=True, check=False,
        )
        assert result.returncode == 0, (
            "the retention default is not gitignored, so a kept log dirties the "
            "worktree it certifies"
        )
    finally:
        probe.unlink(missing_ok=True)


def test_a_failed_fixture_builder_retains_its_evidence_too(tmp_path):
    """The third refusal path, which kept nothing.

    `_resolve_scanner` and `_scanner_self_test` each set `fail_count` and call
    `_report_raw_log`. The fixture-builder refusal did neither, so the EXIT
    trap's retention rule read `fail_count` as 0 and removed the scratch
    directory holding the only record of the run. That path is reached exactly
    when the harness cannot build the corpus it was about to scan, and the
    resolve and self-test records are then the whole of the evidence.

    The harness runs through a symlink farm so its `REPO_ROOT` — and therefore
    its default retention directory — resolve inside `tmp_path`, which keeps
    this case out of the repository directory the two cases above share. The
    farm also supplies the failure: `$REPO_ROOT/bin/build-source-aware-fixtures.py`
    does not exist under it, so `python3` exits non-zero on the one call this
    case is about and on no other. `CCTALLY_SOURCE_AWARE_RAW_LOG_DIR` stays
    unset, so retention here still depends on the failure count.
    """
    root = Path(__file__).resolve().parents[1]
    farm = tmp_path / "farm"
    (farm / "bin").mkdir(parents=True)
    for name in ("cctally-source-aware-test", "_lib-harness-env.sh",
                 "_lib-golden-diff.sh"):
        (farm / "bin" / name).symlink_to(root / "bin" / name)

    env = dict(os.environ)
    env.pop("CCTALLY_SOURCE_AWARE_RAW_LOG_DIR", None)
    result = subprocess.run(
        [str(farm / "bin" / "cctally-source-aware-test")],
        text=True, capture_output=True, check=False, env=env,
    )

    assert result.returncode != 0, result.stdout
    # `python3 <missing file>` exits 2, and the harness reports the builder's
    # own number rather than the bare "exited non-zero" it used to print.
    assert (
        "FAIL source-aware: fixture builder exit status 2"
    ) in result.stdout, result.stdout
    assert "scanner evidence retained at " in result.stdout, result.stdout

    kept = sorted(
        (farm / ".cctally-remote-state" / "source-aware-evidence")
        .glob("scanner-raw.cctally-source-aware.*.log")
    )
    assert len(kept) == 1, [path.name for path in kept]
    assert kept[0].name in result.stdout, result.stdout
    raw = kept[0].read_text(encoding="utf-8")
    assert raw.splitlines()[0].startswith("resolve attempted"), raw.splitlines()[:3]
    assert "self-test probe=match" in raw
