"""RED/GREEN coverage for provider-aware CLI share snapshots."""
from __future__ import annotations

from datetime import datetime, timezone
import json
import os
from pathlib import Path
import runpy
import stat
import subprocess
import sys
from types import SimpleNamespace

import pytest

from conftest import load_script
from _lib_source_analytics import (
    CodexRangeData,
    CodexReportData,
    CodexReportRow,
    CodexReportSeries,
    SourceResult,
    TokenTotals,
)


UTC = timezone.utc


def _kernel():
    ns = load_script()
    return ns, ns["_share_load_lib"](), ns["_cctally_source_analytics"]


def _period(ls):
    return ls.PeriodSpec(
        start=datetime(2026, 7, 1, tzinfo=UTC),
        end=datetime(2026, 7, 2, tzinfo=UTC),
        display_tz="UTC",
        label="Jul 01 → Jul 02 (UTC)",
    )


def _collision_snapshot(ls):
    return ls.ShareSnapshot(
        cmd="project",
        title="Projects",
        subtitle=None,
        period=_period(ls),
        columns=(
            ls.ColumnSpec(key="project", label="Project", kind="project"),
            ls.ColumnSpec(key="cost", label="$ Cost", align="right"),
        ),
        rows=(
            ls.Row(cells={
                "project": ls.ProjectCell("repo", rank_cost=1.0, identity="root-a"),
                "cost": ls.MoneyCell(1.0),
            }),
            ls.Row(cells={
                "project": ls.ProjectCell("repo", rank_cost=2.0, identity="root-b"),
                "cost": ls.MoneyCell(2.0),
            }),
        ),
        chart=ls.HorizontalBarChart(
            points=(
                ls.ChartPoint("repo", 0.0, 1.0, project_label="repo", project_identity="root-a"),
                ls.ChartPoint("repo", 1.0, 2.0, project_label="repo", project_identity="root-b"),
            ),
            x_label="$ Cost",
        ),
        totals=(),
        notes=(),
        generated_at=datetime(2026, 7, 2, 12, tzinfo=UTC),
        version="1.0.0",
    )


def test_equal_labels_with_distinct_qualified_identities_get_distinct_aliases():
    _ns, ls, _source = _kernel()

    scrubbed = ls._scrub(_collision_snapshot(ls), reveal_projects=False)

    row_labels = [row.cells["project"].label for row in scrubbed.rows]
    point_labels = [point.project_label for point in scrubbed.chart.points]
    assert set(row_labels) == {"project-1", "project-2"}
    assert point_labels == row_labels
    assert all(label != "repo" for label in point_labels)


def test_legacy_none_identity_snapshot_is_byte_stable():
    _ns, ls, _source = _kernel()
    snap = ls.ShareSnapshot(
        cmd="report",
        title="Legacy share",
        subtitle=None,
        period=_period(ls),
        columns=(ls.ColumnSpec(key="label", label="Label"),),
        rows=(ls.Row(cells={"label": ls.TextCell("value")}),),
        chart=None,
        totals=(),
        notes=(),
        generated_at=datetime(2026, 7, 2, 12, tzinfo=UTC),
        version="1.0.0",
    )

    assert ls.render(snap, format="md", theme="light", branding=True) == (
        "---\n"
        "title: Legacy share\n"
        "generated_at: 2026-07-02T12:00:00Z\n"
        "period: 2026-07-01T00:00:00Z..2026-07-02T00:00:00Z\n"
        "panel: report\n"
        "anonymized: false\n"
        "cctally_version: 1.0.0\n"
        "---\n"
        "# Legacy share\n"
        "\n"
        "| Label |\n"
        "|:---|\n"
        "| value |\n"
        "\n"
        "_Generated by [cctally](https://github.com/omrikais/cctally) · v1.0.0 · 2026-07-02T12:00:00Z_\n"
    )


def test_codex_snapshot_labels_source_and_unavailable_reason_in_every_format():
    ns, ls, source = _kernel()
    warning = ns["SourceWarning"]("metadata", "Codex metadata is unavailable.")
    result = ns["SourceResult"]("codex", "unavailable", None, (warning,))

    snap = source.build_source_share_snapshot("project", result, reveal_projects=False)

    assert snap.source == "codex"
    assert snap.source_label == "Codex"
    assert snap.availability == "unavailable"
    assert snap.availability_reason == "Codex metadata is unavailable."
    for fmt in ("md", "html", "svg"):
        rendered = ls.render(snap, format=fmt, theme="light", branding=True)
        assert "Codex" in rendered
        assert "Unavailable: Codex metadata is unavailable." in rendered


def test_populated_codex_report_snapshot_exposes_safe_quota_rows():
    _ns, _ls, source = _kernel()
    at = datetime(2026, 7, 2, 12, tzinfo=UTC)
    result = SourceResult(
        "codex",
        "ok",
        CodexReportData(
            as_of=at,
            series=(CodexReportSeries(
                quota_key="quota:never-render-this-opaque-key",
                slot="five-hour",
                window_minutes=300,
                rows=(CodexReportRow(
                    block_start=datetime(2026, 7, 2, 7, tzinfo=UTC),
                    reset_at=at,
                    used_percent=37.0,
                    cost_usd=4.25,
                    cost_per_percent=4.25 / 37,
                    status="ok",
                ),),
            ),),
            quota_status="ok",
        ),
    )

    snap = source.build_source_share_snapshot("report", result, reveal_projects=False)

    assert [column.key for column in snap.columns] == ["series", "used", "cost"]
    assert len(snap.rows) == 1
    assert snap.rows[0].cells["series"].text == "five-hour · 300m"
    assert snap.rows[0].cells["used"].text == "37.0%"
    assert "quota:never-render-this-opaque-key" not in " ".join(
        getattr(cell, "text", "") for cell in snap.rows[0].cells.values()
    )


def test_range_cost_share_without_breakdown_keeps_truthful_total_in_all_formats():
    _ns, ls, source = _kernel()
    start = datetime(2026, 7, 1, tzinfo=UTC)
    end = datetime(2026, 7, 2, tzinfo=UTC)
    result = SourceResult(
        "codex",
        "ok",
        CodexRangeData(
            start=start,
            end=end,
            totals=TokenTotals(total_tokens=1234, cost_usd=4.25),
            models=(),
            include_breakdown=False,
        ),
    )

    snap = source.build_source_share_snapshot("range-cost", result, reveal_projects=False)

    assert len(snap.rows) == 1
    assert snap.rows[0].cells["model"].text == "Total"
    assert snap.rows[0].cells["tokens"].text == "1,234"
    assert snap.rows[0].cells["cost"].usd == 4.25
    for fmt in ("md", "html", "svg"):
        rendered = ls.render(snap, format=fmt, theme="light", branding=True)
        assert "1,234" in rendered
        assert "$4.25" in rendered


def test_codex_diff_share_keeps_each_native_row_status_and_ab_delta_metrics():
    ns, ls, source = _kernel()
    kernel = ns["_lib_source_analytics"]
    start = datetime(2026, 7, 1, tzinfo=UTC)
    middle = datetime(2026, 7, 1, 12, tzinfo=UTC)
    end = datetime(2026, 7, 2, tzinfo=UTC)
    entry = kernel.QualifiedCodexEntry
    entries = kernel.assign_collision_safe_project_labels((
        entry(
            timestamp=start, source_root_key="root-a", conversation_key="conversation-a",
            project_key="project:" + "a" * 24, project_label="repo", model="gpt-5",
            input_tokens=100, cached_input_tokens=20, output_tokens=30,
            reasoning_output_tokens=5, total_tokens=130, cost_usd=1.0,
        ),
        entry(
            timestamp=middle, source_root_key="root-b", conversation_key="conversation-b",
            project_key="project:" + "b" * 24, project_label="repo", model="gpt-5.5",
            input_tokens=200, cached_input_tokens=100, output_tokens=60,
            reasoning_output_tokens=10, total_tokens=260, cost_usd=3.0,
        ),
    ))
    result = kernel.build_codex_diff_result(
        entries,
        kernel.AnalyticsWindow("A", "calendar", start, middle),
        kernel.AnalyticsWindow("B", "calendar", middle, end),
        show_all=True,
        classify_presence=True,
    )

    snap = source.build_source_share_snapshot("diff", result, reveal_projects=False)
    scrubbed = ls._scrub(snap, reveal_projects=False)
    for fmt in ("md", "html", "svg"):
        rendered = ls.render(scrubbed, format=fmt, theme="light", branding=True)
        metrics = (
            ("A $", "B $", "Δ $", "Cost", "A", "B", "Δ", "Tokens")
            if fmt == "svg" else
            ("A $ Cost", "B $ Cost", "Δ $ Cost", "A Tokens", "B Tokens", "Δ Tokens")
        )
        labels = ("project-",) if fmt == "svg" else ("project-1", "project-2")
        for text in (*metrics, "gpt-5", "gpt-5.5", "dropped", "new", *labels):
            assert text in rendered
        assert "root-a" not in rendered and "root-b" not in rendered


def test_qualified_identity_uses_one_alias_across_cell_column_and_chart():
    _ns, ls, _source = _kernel()
    snap = ls.ShareSnapshot(
        cmd="project",
        title="Projects",
        subtitle=None,
        period=_period(ls),
        columns=(
            ls.ColumnSpec(key="project", label="Project"),
            ls.ColumnSpec(
                key="root-a", label="repo", kind="project",
                project_identity="project:aaaaaaaaaaaaaaaaaaaaaaaa",
            ),
        ),
        rows=(ls.Row(cells={
            "project": ls.ProjectCell(
                "repo", rank_cost=4.0,
                identity="project:aaaaaaaaaaaaaaaaaaaaaaaa",
            ),
            "root-a": ls.MoneyCell(4.0),
        }),),
        chart=ls.HorizontalBarChart(
            points=(ls.ChartPoint(
                "repo", 0.0, 4.0, project_label="repo",
                project_identity="project:aaaaaaaaaaaaaaaaaaaaaaaa",
            ),),
            x_label="$ Cost",
        ),
        totals=(), notes=(),
        generated_at=datetime(2026, 7, 2, 12, tzinfo=UTC), version="1.0.0",
    )

    scrubbed = ls._scrub(snap, reveal_projects=False)

    assert scrubbed.rows[0].cells["project"].label == "project-1"
    assert scrubbed.columns[1].label == "project-1"
    assert scrubbed.chart.points[0].project_label == "project-1"


def test_all_source_share_composes_claude_then_codex_without_all_snapshot(monkeypatch):
    ns, _ls, source = _kernel()
    emitted = []
    monkeypatch.setitem(ns, "_emit", lambda content, *, kind, value: emitted.append(content))
    monkeypatch.setitem(ns, "_share_resolve_version", lambda: "1.0.0")
    args = SimpleNamespace(
        command="project", source="all", format="md", theme="light",
        no_branding=False, reveal_projects=False, output="-", copy=False,
        open_after_write=False, project=None,
    )
    claude = ns["SourceResult"]("claude", "empty", {"projects": []})
    codex = ns["SourceResult"](
        "codex", "unavailable", None,
        (ns["SourceWarning"]("metadata", "Codex metadata is unavailable."),),
    )

    assert source._emit_source_result(args, codex, claude=claude) == 0

    assert len(emitted) == 1
    artifact = emitted[0]
    assert artifact.index("Claude") < artifact.index("Codex")
    assert "No data" in artifact
    assert "Unavailable: Codex metadata is unavailable." in artifact
    assert 'source="all"' not in artifact


@pytest.mark.parametrize("fmt", ("md", "html", "svg"))
@pytest.mark.parametrize(
    ("command", "argv", "handler_name", "payload", "expected"),
    [
        (
            "diff",
            ["diff", "--a", "2026-07-01..2026-07-01", "--b", "2026-07-02..2026-07-02"],
            "_cmd_diff_claude",
            {
                "sections": [{
                    "name": "overall",
                    "rows": [{
                        "label": "Overall",
                        "a": {"cost_usd": 1.25, "tokens_input": 100},
                        "b": {"cost_usd": 2.50, "tokens_input": 200},
                        "delta": {"cost_usd": 1.25, "tokens_input": 100},
                    }],
                }],
            },
            ("$1.25", "$2.50"),
        ),
        (
            "range-cost",
            ["range-cost", "--start", "2026-07-01T00:00:00Z", "--end", "2026-07-02T00:00:00Z"],
            "_cmd_range_cost_claude",
            {
                "start": "2026-07-01T00:00:00Z",
                "end": "2026-07-02T00:00:00Z",
                "matchedEntries": 1,
                "totalCostUSD": 1.25,
                "modelBreakdowns": [{"model": "claude-test", "totalTokens": 123, "costUSD": 1.25}],
            },
            ("claude-test", "123", "$1.25"),
        ),
        (
            "cache-report",
            ["cache-report", "--since", "2026-07-01", "--until", "2026-07-02"],
            "_cmd_cache_report_claude",
            {
                "days": [{"date": "2026-07-01", "cacheHitPercent": 75.0, "cost": 1.25}],
                "totals": {"totalTokens": 123, "cost": 1.25},
            },
            ("2026-07-01", "75.0%", "$1.25"),
        ),
    ],
)
def test_default_claude_share_uses_structured_legacy_adapter(
    monkeypatch, fmt, command, argv, handler_name, payload, expected,
):
    """The newly-shareable Claude commands must not capture terminal bytes."""
    ns, ls, _source = _kernel()
    emitted = []

    def legacy_handler(args):
        assert args.source == "claude"
        assert args.format is None
        assert args.json is True
        args._source_result_sink(payload)
        return 0

    monkeypatch.setitem(ns, handler_name, legacy_handler)
    monkeypatch.setitem(ns, "_share_render_and_emit", lambda snap, _args: emitted.append(snap))

    assert ns["main"]([*argv, "--format", fmt, "--output", "-"]) == 0

    assert len(emitted) == 1
    snap = emitted[0]
    assert snap.source == "claude"
    assert snap.source_label == "Claude"
    rendered = ls.render(snap, format=fmt, theme="light", branding=True)
    for value in expected:
        assert value in rendered


@pytest.mark.parametrize(
    ("command", "payload", "expected"),
    [
        (
            "project",
            {
                "rangeStart": "2026-07-01",
                "rangeEnd": "2026-07-02",
                "totals": {"costUsd": 3.0},
                "projects": [{
                    "displayKey": "claude-project",
                    "inputTokens": 10,
                    "outputTokens": 20,
                    "cacheWriteTokens": 30,
                    "cacheReadTokens": 40,
                    "costUsd": 3.0,
                }],
            },
            ("claude-project", "100", "$3.00"),
        ),
        (
            "report",
            {
                "trend": [{
                    "weekStartDate": "2026-07-01",
                    "weeklyPercent": 37.0,
                    "weeklyCostUSD": 3.0,
                    "dollarsPerPercent": 3.0 / 37.0,
                }],
            },
            ("Jul 01", "37.0%", "$3.00"),
        ),
    ],
)
def test_claude_legacy_payload_adapters_keep_provider_native_rows(command, payload, expected):
    _ns, ls, source = _kernel()

    snap = source.build_source_share_snapshot(
        command, SourceResult("claude", "ok", payload), reveal_projects=False,
    )

    rendered = ls.render(snap, format="md", theme="light", branding=True)
    for value in expected:
        assert value in rendered


@pytest.mark.parametrize(
    ("handler_name", "command", "view_name"),
    [
        ("cmd_codex_daily", "codex-daily", "build_codex_daily_view"),
        ("cmd_codex_monthly", "codex-monthly", "build_codex_monthly_view"),
        ("cmd_codex_weekly", "codex-weekly", "build_codex_weekly_view"),
        ("cmd_codex_session", "codex-session", "build_codex_session_view"),
    ],
)
def test_codex_reports_render_empty_share_before_legacy_no_data_sentinel(
    monkeypatch, handler_name, command, view_name,
):
    ns, ls, _source = _kernel()
    codex = ns["_cctally_codex"]
    start = datetime(2026, 7, 1, tzinfo=UTC)
    end = datetime(2026, 7, 2, tzinfo=UTC)
    emitted = []
    empty_view = SimpleNamespace(
        rows=(), total_cost_usd=0.0, total_tokens=0,
        total_sessions=0, period_start=start, period_end=end,
        display_tz_label="UTC",
    )
    monkeypatch.setitem(ns, "load_config", lambda *_args: {})
    monkeypatch.setitem(ns, "resolve_display_tz", lambda *_args: None)
    monkeypatch.setitem(ns, "_parse_cli_date_range", lambda *_args, **_kwargs: (start, end))
    monkeypatch.setitem(ns, "get_codex_entries", lambda *_args: [])
    monkeypatch.setitem(ns, view_name, lambda *_args, **_kwargs: empty_view)
    monkeypatch.setitem(ns, "get_week_start_name", lambda *_args: "monday")
    monkeypatch.setitem(ns, "_share_render_and_emit", lambda snap, _args: emitted.append(snap))
    monkeypatch.setitem(ns, "_emit_codex_no_data", lambda *_args: pytest.fail("legacy sentinel ran"))
    args = SimpleNamespace(
        config=None, tz=None, timezone=None, compact=False, speed="auto",
        order="asc", breakdown=False, json=False, format="md", theme="light",
        no_branding=False, reveal_projects=False, output="-", copy=False,
        open_after_write=False,
    )

    assert getattr(codex, handler_name)(args) == 0

    assert len(emitted) == 1
    snap = emitted[0]
    assert snap.source == "codex"
    assert snap.source_label == "Codex"
    assert snap.availability == "empty"
    for fmt in ("md", "html", "svg"):
        rendered = ls.render(snap, format=fmt, theme="light", branding=True)
        assert "Codex" in rendered
        assert "No data" in rendered


def test_source_aware_fixture_builder_has_every_state_format_and_no_canaries(tmp_path):
    root = Path(__file__).resolve().parents[1]
    out = tmp_path / "source-aware"
    builder = root / "bin" / "build-source-aware-fixtures.py"
    builder_ns = runpy.run_path(str(builder))
    builder_source = builder.read_text(encoding="utf-8")

    assert '"/raw-path-canary/source-root-canary"' in builder_source
    assert '"repository-canary/project-canary"' in builder_source
    # The canonical artifacts must exercise public source command routes, not
    # call the source emitter with hand-assembled provider results.
    assert "SOURCE_HANDLERS" in builder_source
    assert "CODEX_REPORT_HANDLERS" in builder_source
    assert "_emit_source_result(" not in builder_source
    assert "def _claude_result(" not in builder_source
    assert "_build_codex_share_snapshot(" not in builder_source

    result = subprocess.run(
        [sys.executable, str(builder), "--out", str(out)],
        text=True, capture_output=True, check=False,
    )

    assert result.returncode == 0, result.stderr
    matrix = builder_ns["CANONICAL_MATRIX"]
    expected = builder_ns["expected_artifact_paths"]()
    actual = {path.relative_to(out) for path in out.rglob("*.golden")}
    assert actual == expected
    assert len(matrix) == 38
    assert len(expected) == 190
    source_commands = {case.command for case in matrix if case.family == "source"}
    assert source_commands == {"project", "diff", "range-cost", "cache-report", "report"}
    codex_commands = {case.command for case in matrix if case.family == "codex-report"}
    assert codex_commands == {"codex-daily", "codex-monthly", "codex-weekly", "codex-session"}
    rendered = "\n".join(path.read_text(encoding="utf-8") for path in out.rglob("*.golden"))
    for canary in builder_ns["CANARIES"]:
        assert canary not in rendered

    # Diff goldens are semantic acceptance artifacts, not merely a file-count
    # matrix: every format must preserve the two-window compatible quantities
    # plus representative native row identities/statuses.
    for case in ("source-diff-codex-populated", "source-diff-all-claude-empty"):
        for fmt in ("md", "html", "svg", "terminal"):
            artifact = (out / case / f"output.{fmt}.golden").read_text(encoding="utf-8")
            expected = (
                ("A $", "B $", "Δ", "tokens", "gpt-5", "project", "changed", "new")
                if fmt == "terminal" else
                (("A $", "B $", "Δ $", "Cost", "A", "B", "Δ", "Tokens",
                  "gpt-5", "project-", "changed", "new") if fmt == "svg" else
                 ("A $ Cost", "B $ Cost", "Δ $ Cost", "A Tokens", "B Tokens", "Δ Tokens",
                  "gpt-5", "project-1", "changed", "new"))
            )
            for text in expected:
                assert text in artifact


def test_source_aware_fixture_builder_uses_real_legacy_handlers_and_payloads(tmp_path):
    """All-source artifacts retain handler-produced Claude JSON, not a stub."""
    root = Path(__file__).resolve().parents[1]
    builder = root / "bin" / "build-source-aware-fixtures.py"
    builder_source = builder.read_text(encoding="utf-8")

    # The builder may replace deterministic data/cache/time dependencies, but
    # it must route through the installed legacy command function and its
    # structured-result sink.  A hand-built JSON payload or handler-shaped
    # stub makes the source-aware artifacts stop testing the command boundary.
    assert "def _legacy_payload(" not in builder_source
    assert "def legacy_handler(" not in builder_source
    assert "setattr(module, legacy_handler_name" not in builder_source
    assert "LEGACY_HANDLER_TARGETS" in builder_source

    out = tmp_path / "source-aware"
    result = subprocess.run(
        [sys.executable, str(builder), "--out", str(out)],
        text=True, capture_output=True, check=False,
    )
    assert result.returncode == 0, result.stderr

    for command in ("project", "diff", "range-cost", "cache-report", "report"):
        case_dir = f"source-{command}-all-codex-empty"
        for fmt in ("md", "html", "svg", "terminal", "json"):
            generated = out / case_dir / f"output.{fmt}.golden"
            committed = root / "tests" / "fixtures" / "source-aware" / generated.relative_to(out)
            assert generated.read_bytes() == committed.read_bytes()
        claude = json.loads((out / case_dir / "output.json.golden").read_text(encoding="utf-8"))["sources"][0]
        payload = claude["data"]
        assert claude["source"] == "claude"
        assert claude["status"] == "ok"
        if command == "project":
            assert payload["projects"][0]["inputTokens"] > 0
            assert payload["totals"]["costUsd"] > 0
        elif command == "diff":
            overall = payload["sections"][0]["rows"][0]
            assert overall["a"]["cost_usd"] > 0
            assert overall["b"]["cost_usd"] > 0
        elif command == "range-cost":
            assert payload["modelBreakdowns"][0]["totalTokens"] > 0
            assert payload["totalCostUSD"] > 0
        elif command == "cache-report":
            assert payload["days"][0]["totalTokens"] > 0
            assert payload["totals"]["cost"] > 0
        else:
            assert payload["trend"][0]["weeklyPercent"] > 0
            assert payload["trend"][0]["weeklyCostUSD"] > 0


def test_source_aware_codex_report_goldens_are_plain_under_ci_color_env(tmp_path):
    """Codex-report terminal goldens must stay ANSI-free even when the ambient
    environment forces color. GitHub Actions sets $CI, which
    _supports_color_stdout() treats as color-on; the Codex-report handlers take
    no color arg (unlike the source-family), so the builder must neutralize
    color itself. Without that, the committed plain goldens diverge on CI —
    the exact regression this guards. Non-vacuous: building under CI=1/
    FORCE_COLOR=1 without the NO_COLOR pin re-introduces the \\x1b codes and
    fails the byte-compare below.
    """
    root = Path(__file__).resolve().parents[1]
    builder = root / "bin" / "build-source-aware-fixtures.py"
    out = tmp_path / "source-aware"

    env = {**os.environ, "CI": "1", "FORCE_COLOR": "1"}
    result = subprocess.run(
        [sys.executable, str(builder), "--out", str(out)],
        text=True, capture_output=True, check=False, env=env,
    )
    assert result.returncode == 0, result.stderr

    committed = root / "tests" / "fixtures" / "source-aware"
    for command in ("codex-daily", "codex-monthly", "codex-weekly", "codex-session"):
        rel = Path(f"codex-report-{command}-populated") / "output.terminal.golden"
        generated = (out / rel).read_bytes()
        assert b"\x1b" not in generated, f"{rel} gained ANSI codes under CI color env"
        assert generated == (committed / rel).read_bytes(), rel


def test_source_aware_harness_diffs_committed_artifacts_and_scans_canaries():
    root = Path(__file__).resolve().parents[1]
    harness = root / "bin" / "cctally-source-aware-test"
    harness_source = harness.read_text(encoding="utf-8")

    assert "--manifest" in harness_source
    assert "--canaries" in harness_source

    result = subprocess.run(
        [str(harness)], text=True, capture_output=True, check=False,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "passed: 190   failed: 0" in result.stdout


def test_source_aware_fixture_builder_and_harness_are_executable_regular_scripts():
    root = Path(__file__).resolve().parents[1]

    for script in (
        root / "bin" / "build-source-aware-fixtures.py",
        root / "bin" / "cctally-source-aware-test",
    ):
        mode = script.stat().st_mode
        assert stat.S_ISREG(mode), script
        assert mode & (stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH), script


def test_source_aware_harness_uses_bash_3_compatible_read_loops():
    root = Path(__file__).resolve().parents[1]
    harness_source = (root / "bin" / "cctally-source-aware-test").read_text(encoding="utf-8")

    assert "mapfile" not in harness_source
    assert "while IFS= read -r" in harness_source


def test_source_aware_harness_is_a_required_bundle_gate():
    root = Path(__file__).resolve().parents[1]
    bundle = (root / "bin" / "cctally-test-all").read_text(encoding="utf-8")

    assert "required_harnesses=(codex-quota source-aware)" in bundle


def _live_release_version(root: Path) -> str:
    """First stamped ``## [x.y.z]`` header in the repo CHANGELOG."""
    for line in (root / "CHANGELOG.md").read_text(encoding="utf-8").splitlines():
        if line.startswith("## [") and "Unreleased" not in line:
            return line.split("[", 1)[1].split("]", 1)[0]
    raise AssertionError("no stamped CHANGELOG version found")


def test_source_aware_branded_goldens_are_version_pinned_not_release_coupled():
    """The branded md/html/svg goldens must embed a fixed stub version, never
    the live CHANGELOG version.

    Regression guard for the v1.69.0 break: the builder read
    ``_release_version()`` (latest CHANGELOG entry) unpinned, so the committed
    goldens froze whatever version was current at generation time and every
    subsequent release re-staled all 74 branded goldens — reddening dev + public
    CI on the release commit itself. The builder now pins a ``9.9.9`` stub
    (bin/build-source-aware-fixtures.py), mirroring the share-v2 harness.

    Non-vacuous: the assertion below fails the instant the pin is removed, since
    the live repo version (1.69.x+) is never ``9.9.9``.
    """
    root = Path(__file__).resolve().parents[1]
    live = _live_release_version(root)
    assert live != "9.9.9", "repo happens to be at the stub version; pick another stub"

    branded = (
        root / "tests" / "fixtures" / "source-aware"
        / "codex-report-codex-daily-populated" / "output.md.golden"
    ).read_text(encoding="utf-8")
    assert "cctally_version: 9.9.9" in branded
    assert f"cctally_version: {live}" not in branded

    # The builder itself must carry the pin so any regeneration self-pins.
    builder_source = (root / "bin" / "build-source-aware-fixtures.py").read_text(encoding="utf-8")
    assert "CCTALLY_TEST_CHANGELOG_PATH" in builder_source
    assert "os.get_terminal_size" in builder_source
