"""The TUI combination list has one owner, and the harness refuses a bad one.

#769 S4 #796. `bin/cctally-tui-test` and `bin/build-tui-fixtures.py` each
carried their own copy of the `(state, variant, size)` list, and the copies
drifted to 24 entries in the harness against 9 in the builder — so fifteen of
the renders the suite checks were regenerated by nobody, and their goldens
could only ever be edited by hand.

The builder is now the single owner and emits the list as four-column TSV;
the harness reads that. Checking only the builder's exit status would not be
enough, because the harness starts `fail=0` and passes while that stays zero:
an empty manifest that exited 0 would run no case and report success. So
every malformed shape is refused before the first render, and those refusals
are what most of this module drives.
"""
from __future__ import annotations

import pathlib
import shutil
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
BIN = REPO / "bin"
FIXTURES = REPO / "tests" / "fixtures" / "tui"
GOLDEN = FIXTURES / "golden"

sys.path.insert(0, str(BIN))
from _lib_tui_manifest import FIELDS, validate_manifest  # noqa: E402
sys.path.pop(0)

#: What `bin/cctally-tui-test` passes as its expected record count. Stated
#: here as a literal on purpose: deriving it from the builder would make this
#: module agree with any list the builder happens to hold.
EXPECTED_RECORDS = 24


_MANIFEST_CACHE = {}


def _manifest_text() -> str:
    """One subprocess for the module: every case reads the same emission."""
    if "text" in _MANIFEST_CACHE:
        return _MANIFEST_CACHE["text"]
    proc = subprocess.run(
        [sys.executable, str(BIN / "build-tui-fixtures.py"), "--manifest"],
        capture_output=True, text=True, check=False,
    )
    assert proc.returncode == 0, proc.stderr[-2000:]
    _MANIFEST_CACHE["text"] = proc.stdout
    return proc.stdout


def test_the_builder_emits_the_whole_combination_list():
    text = _manifest_text()
    problems = validate_manifest(
        text, fixtures_dir=FIXTURES, golden_dir=GOLDEN,
        expected_records=EXPECTED_RECORDS,
    )
    assert problems == []


def test_every_emitted_record_carries_an_explicit_display_timezone():
    """`TZ=UTC` is wrong rather than merely inconsistent.

    `_local_tz_name` accepts only a value containing a slash and otherwise
    falls back to host-local, so a zone spelled `UTC` would silently leave the
    render on the ambient zone — which is the exposure the pinning removes.
    """
    zones = {
        line.split("\t")[3] for line in _manifest_text().splitlines() if line
    }
    assert zones == {"Etc/UTC", "America/New_York"}, zones
    assert all("/" in zone for zone in zones)


def test_the_deliberate_non_utc_regression_case_keeps_its_zone():
    records = [line.split("\t") for line in _manifest_text().splitlines()]
    non_utc = [r for r in records if r[3] != "Etc/UTC"]
    assert [r[0] for r in non_utc] == ["iana_tz"]
    assert non_utc[0][3] == "America/New_York"


def test_the_manifest_mode_writes_nothing(tmp_path):
    """Side-effect-free by contract, proven by running it somewhere empty.

    `GOLDEN.mkdir(parents=True, exist_ok=True)` used to run at import, so the
    manifest path created directories before it printed anything. The copy
    below makes `REPO` the temporary directory, so any such write lands where
    this case can see it.
    """
    staged_bin = tmp_path / "bin"
    staged_bin.mkdir()
    shutil.copy2(BIN / "build-tui-fixtures.py", staged_bin)
    proc = subprocess.run(
        [sys.executable, str(staged_bin / "build-tui-fixtures.py"),
         "--manifest"],
        capture_output=True, text=True, check=False, cwd=tmp_path,
    )
    assert proc.returncode == 0, proc.stderr[-2000:]
    assert proc.stdout.count("\n") == EXPECTED_RECORDS
    created = sorted(
        path.relative_to(tmp_path).as_posix()
        for path in tmp_path.rglob("*")
        if path.name not in ("bin", "build-tui-fixtures.py")
        and "__pycache__" not in path.parts
    )
    assert created == [], created


def test_the_harness_reads_the_manifest_and_keeps_no_second_copy():
    harness = (BIN / "cctally-tui-test").read_text(encoding="utf-8")
    assert "--manifest" in harness, "the harness no longer reads a manifest"
    assert "build-tui-fixtures.py" in harness
    assert "_lib_tui_manifest.py" in harness
    # The drifted second copy was a `COMBOS=(...)` array of quoted triples.
    assert "COMBOS=(" not in harness
    # Bash 3.2 has no `mapfile`/`readarray`, so the read loop must not use
    # them. Comment lines are excluded deliberately: #776's first scan of this
    # estate reported two harnesses using `mapfile` and both matches were
    # comments, one of them saying in so many words that the code uses a
    # portable `while read` loop instead.
    code = [
        line for line in harness.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    offenders = [
        line for line in code
        if "mapfile" in line or "readarray" in line
    ]
    assert offenders == [], offenders


def test_the_builder_refuses_an_unrecognised_argument():
    """A typo'd flag must not run a twenty-four-combination regeneration.

    `--manifest` was recognised by membership anywhere in `sys.argv` and every
    other argument was discarded, so `--manifets` fell through to `build()`
    and rewrote every golden in the caller's tree.
    """
    for argv in (["--manifets"], ["--manifest", "--extra"], ["-h"]):
        proc = subprocess.run(
            [sys.executable, str(BIN / "build-tui-fixtures.py"), *argv],
            capture_output=True, text=True, check=False,
        )
        assert proc.returncode == 2, (argv, proc.returncode, proc.stdout[:400])
        assert proc.stdout == "", (argv, proc.stdout[:400])
        assert "unrecognised arguments" in proc.stderr, (argv, proc.stderr)


def test_the_validator_signals_a_usage_error_only_on_stderr():
    """The premise the harness's old emptiness test rested on.

    `bin/cctally-tui-test` used to decide the manifest was usable when the
    validator's STDOUT was empty. `main` returns 2 with a usage message on
    stderr for a wrong argument count, and an unhandled exception writes a
    traceback to stderr and nothing to stdout, so in both cases the emptiness
    test was true and the harness rendered against an unvalidated manifest.
    This pins the shape that made that possible, so a later change to the
    validator's streams cannot quietly restore it.
    """
    proc = subprocess.run(
        [sys.executable, str(BIN / "_lib_tui_manifest.py"), "one", "two"],
        capture_output=True, text=True, check=False,
    )
    assert proc.returncode == 2, proc.returncode
    assert proc.stdout == "", proc.stdout[:400]
    assert "usage:" in proc.stderr, proc.stderr[:400]


def test_the_harness_branches_on_the_validator_exit_status():
    """Read from the harness text, because running it costs 24 renders.

    The property is behavioural and the check is textual, which is a real
    limitation and the reason it is stated here rather than implied: this case
    cannot see a harness that captures the status correctly and then ignores
    it. What it does see is the two shapes that produced the defect — a
    verdict read from the emptiness of a captured string, and a status read
    back with `$?` after a negated `if`, where `$?` is the status of the
    negation and is always 0 on the failing branch.
    """
    harness = (BIN / "cctally-tui-test").read_text(encoding="utf-8")
    code = [
        line for line in harness.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    joined = "\n".join(code)
    assert 'manifest_status=$?' in joined, (
        "the harness must capture the validator's own exit status")
    assert '[ "$manifest_status" -ne 0 ]' in joined, (
        "the harness must branch on that status, not on captured output")
    assert 'manifest_error' not in joined, (
        "the emptiness-of-stdout verdict is back; a crashed validator reads "
        "as a pass under it")
    assert 'builder_status=$?' in joined, (
        "the builder's own exit status must be captured too")
    negated = [
        line for line in code
        if line.lstrip().startswith("if !") and "python3" in line
    ]
    assert negated == [], (
        "`$?` inside a negated `if` is the status of the negation, so the "
        "reported status is always 0: " + repr(negated))


def _valid_records() -> list:
    return [line.split("\t") for line in _manifest_text().splitlines()]


def _render(records) -> str:
    return "".join("\t".join(record) + "\n" for record in records)


def _problems(text, *, expected=EXPECTED_RECORDS):
    return validate_manifest(
        text, fixtures_dir=FIXTURES, golden_dir=GOLDEN,
        expected_records=expected,
    )


def test_a_malformed_record_is_refused():
    records = _valid_records()
    records[3] = records[3][:3]
    problems = _problems(_render(records))
    assert any("has 3 fields" in problem for problem in problems), problems


def test_a_blank_required_field_is_refused():
    records = _valid_records()
    records[2][1] = "   "
    problems = _problems(_render(records))
    assert any("blank variant" in problem for problem in problems), problems


def test_a_duplicate_combination_is_refused():
    records = _valid_records()
    records[1] = list(records[0])
    problems = _problems(_render(records))
    assert any("duplicates" in problem for problem in problems), problems


def test_a_missing_snapshot_module_is_refused():
    records = _valid_records()
    records[0][0] = "no_such_state"
    problems = _problems(_render(records))
    assert any("missing snapshot module" in problem for problem in problems), \
        problems


def test_a_missing_golden_is_refused():
    records = _valid_records()
    records[0][2] = "1x1"
    problems = _problems(_render(records))
    assert any("missing golden" in problem for problem in problems), problems


def test_an_unterminated_trailing_record_is_refused():
    problems = _problems(_render(_valid_records()).rstrip("\n"))
    assert any("unterminated" in problem for problem in problems), problems


def test_an_empty_manifest_is_refused():
    """The vacuous-green case the harness's `fail=0` could not see."""
    problems = _problems("")
    assert any("expected 24" in problem for problem in problems), problems


def test_a_truncated_manifest_is_refused():
    records = _valid_records()[:-1]
    problems = _problems(_render(records))
    assert any("23 records, expected 24" in problem for problem in problems), \
        problems


def test_the_field_order_is_the_one_the_harness_reads():
    """The harness reads `state variant size tz` positionally."""
    assert FIELDS == ("state", "variant", "size", "tz")
