"""Auto-generated by bin/build-readme-fixtures.py — do not hand-edit.

Loaded by `cctally tui --render-once --snapshot-module …` per the dev path.
Exports SNAPSHOT (required) and may export RUNTIME_OVERRIDES (optional).
"""
from __future__ import annotations

# DataSnapshot is defined inside bin/cctally; we lazy-import to keep this
# module loadable by tests that don't have the binary on PYTHONPATH.
import importlib.util as _ilu
import importlib.machinery as _ilm
import sys as _sys
from pathlib import Path as _Path

# Walk up from this snapshot file to find bin/cctally. The earlier
# `parents[3]` form only worked when the snapshot lived at the default
# committed path (tests/fixtures/readme/tui_snapshot.py). For a custom
# `--tui-snapshot` path, parents[3] resolves outside the repo and the
# import fails before the tui renderer runs.
_HERE = _Path(__file__).resolve().parent
_BIN = None
for _p in [_HERE, *_HERE.parents]:
    _candidate = _p / "bin" / "cctally"
    if _candidate.is_file():
        _BIN = _candidate
        break
if _BIN is None:
    raise RuntimeError(
        "could not locate bin/cctally walking up from "
        f"{_HERE}; place the snapshot inside the cctally repo"
    )
_spec = _ilu.spec_from_loader(
    "_cctally_for_tui_snapshot",
    _ilm.SourceFileLoader("_cctally_for_tui_snapshot", str(_BIN)),
)
_mod = _ilu.module_from_spec(_spec)
_sys.modules.setdefault("_cctally_for_tui_snapshot", _mod)
_spec.loader.exec_module(_mod)

DataSnapshot = _mod.DataSnapshot

SNAPSHOT = DataSnapshot.synthesize_for_marketing(as_of_iso="2026-05-07T14:00:00Z")

RUNTIME_OVERRIDES = {}
